/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Edgar Jakumeit
/// </summary>

using System.Collections;
using System.Collections.Generic;

/// <summary>
/// Rudimentary implementation of a LinkedHashMap as known from Java in C# (implementing the IDictionary<TKey,TValue> class, but not inheriting from the Dictionary class)
/// (TODO: unit tests - could be generated by AI)
/// </summary>
public class LinkedHashMap<TKey, TValue> : IDictionary<TKey, TValue> /*,ICollection<KeyValuePair<TKey, TValue>>, IEnumerable<KeyValuePair<TKey, TValue>>, IEnumerable*/
                                                                     /*,IDictionary, ICollection, IReadOnlyDictionary<TKey, TValue>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>*/
{
    Dictionary<TKey, LinkedListNode<KeyValuePair<TKey, TValue>>> unorderedDictionary; // replacement for the HashMap/Dictionary, pointing to the LinkedListNode so that removal is an O(1)-operation
    LinkedList<KeyValuePair<TKey, TValue>> orderedLinkedList; // for ensuring iteration order is the same as addition order, LinkedList so that removal is an O(1)-operation

    public LinkedHashMap()
    {
        unorderedDictionary = new Dictionary<TKey, LinkedListNode<KeyValuePair<TKey, TValue>>>();
        orderedLinkedList = new LinkedList<KeyValuePair<TKey, TValue>>();
    }

    public LinkedHashMap(IEnumerable<KeyValuePair<TKey, TValue>> collection)
        : this()
    {
        foreach(KeyValuePair<TKey, TValue> item in collection)
        {
            Add(item.Key, item.Value);
        }
    }

    public static LinkedHashMap<TKey, TValue> FromDictionary<TKeyExt, TValueExt>(IDictionary<TKeyExt, TValueExt> otherDictionary) where TKeyExt : TKey where TValueExt : TValue // static creation method instead of constructor to allow for non-invariant types
    {
        LinkedHashMap<TKey, TValue> linkedHashMap = new LinkedHashMap<TKey, TValue>();

        foreach(KeyValuePair<TKeyExt, TValueExt> item in otherDictionary)
        {
            linkedHashMap.Add(item.Key, item.Value);
        }

        return linkedHashMap;
    }

    // --- ICollection<KeyValuePair<TKey, TValue>> -------------------------------------------

    public int Count
    {
        get { return unorderedDictionary.Count; }
    }

    public bool IsReadOnly
    {
        get { return false; }
    }

    public void Add(KeyValuePair<TKey, TValue> item)
    {
        ((IDictionary<TKey, TValue>)this).Add(item.Key, item.Value);
    }

    public void Clear()
    {
        unorderedDictionary.Clear();
        orderedLinkedList.Clear();
    }

    public bool Contains(KeyValuePair<TKey, TValue> item)
    {
        LinkedListNode<KeyValuePair<TKey, TValue>> node;
        if(unorderedDictionary.TryGetValue(item.Key, out node))
        {
            return node.Value.Value.Equals(item.Value);
        }
        return false;
    }

    public void CopyTo(KeyValuePair<TKey, TValue>[] array, int arrayIndex)
    {
        orderedLinkedList.CopyTo(array, arrayIndex);
    }

    public bool Remove(KeyValuePair<TKey, TValue> item)
    {
        LinkedListNode<KeyValuePair<TKey, TValue>> node;
        bool found = unorderedDictionary.TryGetValue(item.Key, out node);
        if(found)
        {
            unorderedDictionary.Remove(item.Key);
            orderedLinkedList.Remove(node);
            return true;
        }
        return false;
    }

    public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
    {
        return orderedLinkedList.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return orderedLinkedList.GetEnumerator();
    }

    // --- IDictionary<TKey, TValue> -------------------------------------------

    public TValue this[TKey key]
    {
        get { return unorderedDictionary[key].Value.Value; }
        set
        {
            if(unorderedDictionary.ContainsKey(key))
                unorderedDictionary[key].Value = new KeyValuePair<TKey, TValue>(key, value);
            else
            {
                LinkedListNode<KeyValuePair<TKey, TValue>> node = orderedLinkedList.AddLast(new KeyValuePair<TKey, TValue>(key, value));
                unorderedDictionary[key] = node;
            }
        }
    }

    public ICollection<TKey> Keys
    {
        get { return unorderedDictionary.Keys; }
    }

    public ICollection<TValue> Values
    {
        get { throw new System.NotImplementedException(); }
    }

    public void Add(TKey key, TValue value)
    {
        LinkedListNode<KeyValuePair<TKey, TValue>> node = new LinkedListNode<KeyValuePair<TKey, TValue>>(new KeyValuePair<TKey, TValue>(key, value));
        unorderedDictionary.Add(key, node);
        orderedLinkedList.AddLast(node);
    }

    public bool ContainsKey(TKey key)
    {
        return unorderedDictionary.ContainsKey(key);
    }

    public bool Remove(TKey key)
    {
        LinkedListNode<KeyValuePair<TKey, TValue>> node;
        if(unorderedDictionary.TryGetValue(key, out node))
        {
            unorderedDictionary.Remove(key);
            orderedLinkedList.Remove(node);
            return true;
        }
        return false;
    }

    public bool TryGetValue(TKey key, out TValue value)
    {
        LinkedListNode<KeyValuePair<TKey, TValue>> node;
        if(unorderedDictionary.TryGetValue(key, out node))
        {
            value = node.Value.Value;
            return true;
        }
        else
        {
            value = default(TValue);
            return false;
        }
    }
}
