<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph2"
    nsURI="graph2" nsPrefix="graph2">
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//GraphComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//GraphComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gcs" upperBound="-1" eType="#//GraphComponent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphComponent" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
