/*
 GrGen: graph rewrite generator tool.
 Copyright (C) 2005  IPD Goos, Universit"at Karlsruhe, Germany

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */


/**
 * A GrGen Backend which generates C code for a frame-based
 * graph model impl and a frame based graph matcher
 * @author Veit Batz, Rubino Geiss
 * @version $Id$
 */
package de.unika.ipd.grgen.be.C;

import de.unika.ipd.grgen.ir.*;
import java.util.*;

import de.unika.ipd.grgen.Sys;
import de.unika.ipd.grgen.be.Backend;
import de.unika.ipd.grgen.be.BackendException;
import de.unika.ipd.grgen.be.BackendFactory;
import de.unika.ipd.grgen.be.C.fb.AttrTypeDescriptor;
import de.unika.ipd.grgen.be.C.fb.EnumDescriptor;
import de.unika.ipd.grgen.be.C.fb.MoreInformationCollector;
import de.unika.ipd.grgen.util.Attributed;
import de.unika.ipd.grgen.util.Attributes;
import java.io.File;
import java.io.PrintStream;

public class SearchPlanBackend extends MoreInformationCollector implements Backend, BackendFactory {
	
	private final int OUT = 0;
	private final int IN = 1;
	
	protected final boolean emit_subgraph_info = false;
	
	/* binary operator symbols of the C-language */
	// ATTENTION: the forst two shift operations are signed shifts
	// 		the second right shift is signed. This Backend simply gens
	//		C-bitwise-shift-operations on signed integers, for simplicity ;-)
	private String[] opSymbols = {
		null, "||", "&&", "|", "^", "&",
			"==", "!=", "<", "<=", ">", ">=", "<<", ">>", ">>", "+",
			"-", "*", "/", "%", null, null, null, null
	};
	
	//Kann man das entfernen???
	//ToDo: Pruefe das, ob man diese Methode wegschmeissen kann!!!
	
	/**
	 * Method makeEvals
	 *
	 * @param    ps                  a  PrintStream
	 *
	 */
	protected void makeEvals(PrintStream ps) {
		// TODO
	}
	
//	// The unit to generate code for.
//	protected Unit unit;
//	// keine Ahnung wozu das gut sein soll
//	protected Sys system;
//	// The output path as handed over by the frontend.
//	private File path;
	
	/**
	 * Create a new backend.
	 * @return A new backend.
	 */
	public Backend getBackend() throws BackendException {
		return this;
	}
	
	/**
	 * Initializes the FrameBasedBackend
	 * @see de.unika.ipd.grgen.be.Backend#init(de.unika.ipd.grgen.ir.Unit, de.unika.ipd.grgen.Sys, java.io.File)
	 */
	public void init(Unit unit, Sys system, File outputPath) {
		super.init(unit, system, outputPath);
//		this.unit = unit;
//		this.path = outputPath;
//		this.system = system;
//		path.mkdirs();
	}
	
	/**
	 * Starts the C-code Genration of the FrameBasedBackend
	 * @see de.unika.ipd.grgen.be.Backend#generate()
	 */
	public void generate() {
		// Emit an include file for Makefiles
		PrintStream ps = openFile("unit.mak");
		ps.println("#\n# generated by grgen, don't edit\n#");
		ps.println("UNIT_NAME = " + formatId(unit.getIdent().toString()));
		closeFile(ps);
		
		System.out.println("The frame-based GrGen backend...");
		System.out.println("  generating the pattern...");
		
		//gen the C-code of the evals
		StringBuffer sb = new StringBuffer();
		sb.append("/* generated by grgen, don't edit */\n\n");
		sb.append("#include <libfirm/firm.h>\n");
		sb.append("#include <libfirm/ext/grs/grs.h>\n\n");
		genTypes(sb);
		genPatterns(sb);
		writeFile("gen_patterns.c", sb);
		
		System.out.println("  generating XML overview...");
		
		// write an overview of all generated Ids
		ps = openFile("overview.xml");
		writeOverview(ps);
		closeFile(ps);
		
		System.out.println("  done!");
	}
	
	/**
	 * Method genTypes
	 *
	 * @param    sb                  a  StringBuffer
	 *
	 */
	private void genTypes(StringBuffer sb) {
		String indent = "  ";
		StringBuffer initsb = new StringBuffer();
		sb.append("/* nodeTypeMap */ \n");
		initsb.append("/* init node ops and modes */\n");
		initsb.append("static void init() {\n");
		for(Identifiable id : nodeTypeMap.keySet()) {
			String type = id.getIdent().toString();
			sb.append("static ir_op* grs_op_" + type + ";\n");
			initsb.append(indent+"grs_op_" + type + " = ext_grs_lookup_op(\""+ type +"\");\n");
		}
		sb.append("/* nodeTypeMap END */\n\n");
		initsb.append("} /* init node ops and modes */\n");
		sb.append(initsb);
	}
	
	
	/**
	 * Method genPatterns generates the patterns needed by the seach plan
	 * builder. It consists mainly of the left hand side of the rule.
	 *
	 * @param    sb                  a  StringBuffer
	 *
	 */
	private void genPatterns(StringBuffer sb) {
		String indent = "  ";
		for(Action action : unit.getActions()) {
			if(action instanceof Rule) {
				String actionName = action.getIdent().toString();
				
				genConditionFunctions(sb, indent, actionName, (Rule)action);
				
				sb.append("/* functions for building the pattern of action " + actionName + " */\n");
				sb.append("static inline ext_grs_action_t *grs_action_" + actionName + "() {\n");
				sb.append(indent + "ext_grs_action_t *act = ext_grs_new_action(ext_grs_k_rule, \"" +
							  actionName + "\");\n");
				
				genPattern(sb, (Rule)action); // generate the pattern
				
				sb.append(indent + "ext_grs_act_mature(act);\n");
				sb.append(indent + "return act;\n");
				sb.append("} /* " + actionName + " */\n\n\n");
			}
			else
				throw new UnsupportedOperationException(action.toString());
		}
	}
	
	
	/**
	 * Method genConditionFunctions generates the fuctions that evaluate the conditions of an action.
	 *
	 * @param    sb                  a  StringBuffer
	 * @param    indent              a  String
	 * @param    actionName          a  String
	 * @param    rule                a  Rule
	 *
	 */
	private void genConditionFunctions(StringBuffer sb, String indent, String actionName, Rule rule) {
		sb.append("/* functions for evaluation of conditions of action " + actionName + " */\n");
		// conditions for L
		genConditionFunction(sb, indent, rule.getLeft());
		
		// conditions  for NACs
		for(PatternGraph neg : rule.getNegs()) {
			genConditionFunction(sb, indent, neg);
		}
		sb.append("\n");
	}
	
	
	private void genConditionFunction(StringBuffer sb, String indent, PatternGraph graph) {
		for(Expression cond : graph.getConditions()) {
			sb.append("static int grs_cond_func_" + cond.getId() + "() {\n");
			sb.append(indent + "return ");
			genConditionEval(sb, cond);
			sb.append("\n");
			sb.append("}\n");
		}
	}
	
	
	/**
	 * Method genPattern generates pattern graph for one rule.
	 *
	 * @param    sb                  a  StringBuffer
	 * @param    rule                a  Rule
	 *
	 */
	private void genPattern(StringBuffer sb, Rule rule) {
		String indent = "  ";
		
		// code for the pattern graph
		sb.append(indent + "{ /* L */\n");
		genPatternGraph(sb, indent+"  ", "ext_grs_act_get_pattern", Collections.EMPTY_SET, rule.getLeft());
		
		
		// code for the negative graphs
		sb.append(indent + "  /* The negative parts of the pattern */\n");
		int i = 0;
		for(PatternGraph neg : rule.getNegs()) {
			sb.append(indent + "  { /* NAC " + i + "  */\n");
			genPatternGraph(sb, indent+"    ", "ext_grs_act_impose_negative", rule.getLeft().getNodes(), neg);
			sb.append(indent + "  } /* NAC " + i + "  */\n");
			sb.append("\n");
			i++;
		}
		sb.append(indent + "} /* L */\n\n");
	}
	
	
	/**
	 * Method genPatternGraph generates code for a L, or a NAC graph.
	 *
	 * @param    sb                  a  StringBuffer
	 * @param    indent              a  String
	 * @param    funcName            a  String containing the C-name for getting the graph
	 * @param    parentNodes         a  Collection<Node> of the nodes of the parent graph
	 * @param    graph               a  Graph
	 *
	 */
	private void genPatternGraph(StringBuffer sb, String indent, String funcName,
								 Collection<Node> parentNodes, PatternGraph graph) {
		sb.append(indent + "ext_grs_graph_t *pattern = " + funcName + "(act);\n\n");
		
		// nodes
		sb.append(indent + "/* The nodes of the pattern */\n");
		for(Node node : graph.getNodes()) {
			if(parentNodes.contains(node))
				continue; // the node is already contained in the parent graph (L)
			String name = node.getIdent().toString();
			String type = node.getNodeType().getIdent().toString();
			
			sb.append(indent + "/* TODO typeof("+name+") = " + type +
						  " \\ " + node.getConstraints()  +"*/\n"); // TODO make type constraints
			sb.append(indent + "ext_grs_node_t *" + name +
						  " = ext_grs_act_add_node(pattern, \"" +
						  name + "\", grs_op_"+type+", grs_mode_XXX);\n");
		}
		sb.append("\n");
		
		//edges
		sb.append(indent + "/* The edges of the pattern */\n");
		for(Edge edge : graph.getEdges()) {
			String name = edge.getIdent().toString().replace('$','_');
			Node src = graph.getSource(edge);
			Node tgt = graph.getTarget(edge);
			sb.append(indent + "ext_grs_edge_t *" + name +
						  " = ext_grs_act_add_edge(pattern, \"" + name +
						  "\", ext_grs_NO_EDGE_POS, " + src.getIdent() + ", " +
						  tgt.getIdent() + ");\n");
		}
		sb.append("\n");
		
		// code for the conditions
		genConditions(sb, indent, graph);
	}
	
	
	/**
	 * Method genConditions
	 *
	 * @param    sb                  a  StringBuffer
	 * @param    indent              a  String
	 * @param    graph               a  PatternGraph
	 *
	 */
	private void genConditions(StringBuffer sb, String indent, PatternGraph graph) {
		sb.append(indent + "/* The conditions of the pattern */\n");
		for(Expression cond : graph.getConditions()) {
			String indent2 = indent + "  ";
			Set<Node> nodes = new HashSet<Node>();
			Set<Edge> edges = new HashSet<Edge>();
			
			collectNodesnEdges(nodes, edges, cond);
			
			sb.append(indent + "{ /* if */\n");
			
			sb.append(indent2 + "static ext_grs_node_t *nodes[" + nodes.size() + "] = ");
			genSet(sb, nodes);
			sb.append("\n");
			sb.append(indent2 + "static ext_grs_node_t *edges[" + edges.size() + "] = ");
			genSet(sb, edges);
			sb.append("\n\n");
			
			sb.append(indent2 + "ext_grs_register_condition(pattern, grs_cond_func_"
						  + cond.getId() + ", " +
						  nodes.size() + ", nodes, " + edges.size() + ", edges);\n");
			
			sb.append(indent + "} /* if */\n\n");
		}
	}
	
	/**
	 * Method genSet dumps C-like Set representaion.
	 *
	 * @param    sb                  a  StringBuffer
	 * @param    set                 a  Set
	 *
	 */
	private void genSet(StringBuffer sb, Set<? extends Entity> set) {
		sb.append('{');
		for(Iterator<? extends Entity> i = set.iterator(); i.hasNext(); ) {
			sb.append(i.next().getIdent().toString());
			if(i.hasNext())
				sb.append(", ");
		}
		sb.append('}');
	}
	
	
	/**
	 * Method collectNodesnEdges extracts the nodes and edges occuring in an Expression.
	 *
	 * @param    nodes               a  Set to contain the nodes of cond
	 * @param    edges               a  Set to contain the edges of cond
	 * @param    cond                an Expression
	 *
	 */
	private void collectNodesnEdges(Set<Node> nodes, Set<Edge> edges, Expression cond) {
		if(cond instanceof Qualification) {
			Entity entity = ((Qualification)cond).getOwner();
			if(entity instanceof Node)
				nodes.add((Node)entity);
			else if(entity instanceof Edge)
				edges.add((Edge)entity);
			else
				throw new UnsupportedOperationException("Unsupported Entity (" + entity + ")");
		}
		else if(cond instanceof Operator)
			for(Expression child : ((Operator)cond).getWalkableChildren())
				collectNodesnEdges(nodes, edges, child);
	}
	
	
	private void genConditionEval(StringBuffer sb, Expression cond) {
		
		if(cond instanceof Operator){
			Operator op = (Operator)cond;
			switch (op.arity()) {
				case 1:
					genConditionEval(sb, op.getOperand(0));
					break;
				case 2:
					genConditionEval(sb, op.getOperand(0));
					sb.append(" " + opSymbols[op.getOpCode()] + " ");
					genConditionEval(sb, op.getOperand(1));
					break;
				case 3:
					if(op.getOpCode()==Operator.COND) {
						sb.append("(");
						genConditionEval(sb, op.getOperand(0));
						sb.append(") ? (");
						genConditionEval(sb, op.getOperand(1));
						sb.append(") : (");
						genConditionEval(sb, op.getOperand(1));
						sb.append(")");
						break;
					}
				default: throw new UnsupportedOperationException("Unsupported Operation arrity (" + op.arity() + ")");
			}
		}
		else if(cond instanceof Qualification) {
			Qualification qual = (Qualification)cond;
			//sb.append(qual.getOwner().getIdent() + "." + qual.getMember().getIdent());
			sb.append("ext_grs_get_pattern_nodes_image( index of "+ qual.getOwner().getIdent() + ")." + qual.getMember().getIdent());
		}
		else if(cond instanceof Constant) {
			Constant con = (Constant)cond;
			sb.append(con.getValue());
		}
		else throw new UnsupportedOperationException("Unsupported expression type (" + cond + ")");
	}
}
