/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ast.type
{

	using System.Collections.Generic;
	using System.Diagnostics;

	using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
	using MatchClassAutoNode = de.unika.ipd.grgen.ast.MatchClassAutoNode;
	using MatchClassFilterCharacter = de.unika.ipd.grgen.ast.MatchClassFilterCharacter;
	using DeclNode = de.unika.ipd.grgen.ast.decl.DeclNode;
	using MatchClassFilterAutoGeneratedDeclNode = de.unika.ipd.grgen.ast.decl.executable.MatchClassFilterAutoGeneratedDeclNode;
	using MatchClassFilterFunctionDeclNode = de.unika.ipd.grgen.ast.decl.executable.MatchClassFilterFunctionDeclNode;
	using Operator = de.unika.ipd.grgen.ast.decl.executable.Operator;
	using OperatorDeclNode = de.unika.ipd.grgen.ast.decl.executable.OperatorDeclNode;
	using OperatorEvaluator = de.unika.ipd.grgen.ast.decl.executable.OperatorEvaluator;
	using DummyNodeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.DummyNodeDeclNode;
	using EdgeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.EdgeDeclNode;
	using NodeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.NodeDeclNode;
	using VarDeclNode = de.unika.ipd.grgen.ast.decl.pattern.VarDeclNode;
	using ArrayAccumulationMethodNode = de.unika.ipd.grgen.ast.expr.array.ArrayAccumulationMethodNode;
	using ConnectionCharacter = de.unika.ipd.grgen.ast.pattern.ConnectionCharacter;
	using ConnectionNode = de.unika.ipd.grgen.ast.pattern.ConnectionNode;
	using PatternGraphLhsNode = de.unika.ipd.grgen.ast.pattern.PatternGraphLhsNode;
	using BasicTypeNode = de.unika.ipd.grgen.ast.type.basic.BasicTypeNode;
	using IR = de.unika.ipd.grgen.ir.IR;
	using MatchClassFilterAutoGenerated = de.unika.ipd.grgen.ir.executable.MatchClassFilterAutoGenerated;
	using MatchClassFilterFunction = de.unika.ipd.grgen.ir.executable.MatchClassFilterFunction;
	using PatternGraphLhs = de.unika.ipd.grgen.ir.pattern.PatternGraphLhs;
	using Variable = de.unika.ipd.grgen.ir.pattern.Variable;
	using DefinedMatchType = de.unika.ipd.grgen.ir.type.DefinedMatchType;

	public class DefinedMatchTypeNode : MatchTypeNode
	{
		static DefinedMatchTypeNode()
		{
			SetClassName(typeof(DefinedMatchTypeNode), "defined match type");
		}

		protected internal List<MatchClassFilterCharacter> filters;
		private PatternGraphLhsNode pattern;
		private MatchClassAutoNode auto;

		public DefinedMatchTypeNode(PatternGraphLhsNode pattern)
		{
			this.pattern = pattern;
			BecomeParent(this.pattern);
		}

		public DefinedMatchTypeNode(MatchClassAutoNode auto)
		{
			this.auto = auto;
			BecomeParent(this.auto);
		}

		public override string TypeName
		{
			get
			{
				return "match<class " + Ident.ToString() + ">";
			}
		}

		public virtual void AddFilters(List<MatchClassFilterCharacter> filters)
		{
			this.filters = filters;
		}

		public override ICollection<BaseNode> Children
		{
			get
			{
				IList<BaseNode> children = new List<BaseNode>();
				if(pattern != null)
					children.Add(pattern);
				if(auto != null)
					children.Add(auto);
				return children;
			}
		}

		public override ICollection<string> ChildrenNames
		{
			get
			{
				IList<string> childrenNames = new List<string>();
				if(pattern != null)
					childrenNames.Add("pattern");
				if(auto != null)
					childrenNames.Add("auto");
				return childrenNames;
			}
		}

		protected internal override bool ResolveLocal()
		{
			OperatorDeclNode.MakeBinOp(Operator.EQ, BasicTypeNode.booleanType,
					this, this, OperatorEvaluator.nullEvaluator);
			OperatorDeclNode.MakeBinOp(Operator.NE, BasicTypeNode.booleanType,
					this, this, OperatorEvaluator.nullEvaluator);

			bool autoOk = true;
			if(pattern == null)
			{
				autoOk = auto.Resolve();

				if(autoOk)
				{
					pattern = BecomeParent(auto.PatternGraph);
					auto.FillPatternGraph(pattern);
				}
			}

			bool filtersOk = true;
			foreach(MatchClassFilterCharacter filter in filters)
			{
				if(filter is MatchClassFilterFunctionDeclNode)
					filtersOk &= ((MatchClassFilterFunctionDeclNode)filter).Resolve();
				else
					filtersOk &= ((MatchClassFilterAutoGeneratedDeclNode)filter).Resolve();
			}

			return autoOk & filtersOk;
		}

		protected internal override bool CheckLocal()
		{
			// maybe TODO: check pattern graph member
			foreach(ConnectionCharacter cc in pattern.Connections)
			{
				if(!(cc is ConnectionNode))
					continue;
				ConnectionNode connection = (ConnectionNode)cc;
				if(!(connection.Src is DummyNodeDeclNode)
						|| !(connection.Tgt is DummyNodeDeclNode))
				{
					connection.ReportError("Only single edge declarations without linked nodes allowed in match classes"
							+ " (but " + connection.Edge.Ident + " comes with linked nodes).");
				}
			}
			return CheckFilters();
		}

		private bool CheckFilters()
		{
			bool filtersOk = true;
			foreach(MatchClassFilterCharacter filter in filters)
			{
				if(filter is MatchClassFilterFunctionDeclNode)
					filtersOk &= ((MatchClassFilterFunctionDeclNode)filter).Check();
				else
					filtersOk &= ((MatchClassFilterAutoGeneratedDeclNode)filter).Check();
			}
			bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
			HashSet<string> alreadySeenFilters = new HashSet<string>();
			foreach(MatchClassFilterCharacter fc in filters)
			{
				if(fc is MatchClassFilterAutoGeneratedDeclNode)
				{
					MatchClassFilterAutoGeneratedDeclNode filter = (MatchClassFilterAutoGeneratedDeclNode)fc;
					string filterNameWithEntitySuffix = filter.FilterNameWithEntitySuffix;
					if(alreadySeenFilters.Contains(filterNameWithEntitySuffix))
					{
						Ident.ReportError("The filter " + filterNameWithEntitySuffix
								+ " was already declared, only one declaration is admissible.");
						allFilterEntitiesExistAndAreOfAdmissibleType = false;
					}
					else
						alreadySeenFilters.Add(filterNameWithEntitySuffix);
					allFilterEntitiesExistAndAreOfAdmissibleType &= CheckAutoGeneratedFilter(filter);
				}
			}
			return filtersOk & allFilterEntitiesExistAndAreOfAdmissibleType;
		}

		private bool CheckAutoGeneratedFilter(MatchClassFilterAutoGeneratedDeclNode filter)
		{
			string filterNameWithEntitySuffix = filter.FilterNameWithEntitySuffix;
			switch(filter.name)
			{
			case "orderAscendingBy":
			case "orderDescendingBy":
			{
				bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
				foreach(string filterEntity in filter.entities)
				{
					allFilterEntitiesExistAndAreOfAdmissibleType &= pattern.CheckFilterVariable(Ident,
							filter.name, filterEntity);
				}
				return allFilterEntitiesExistAndAreOfAdmissibleType;
			}
			case "keepOneForEach":
			case "groupBy":
			case "keepSameAsFirst":
			case "keepSameAsLast":
			{
				bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
				foreach(string filterEntity in filter.entities)
				{
					allFilterEntitiesExistAndAreOfAdmissibleType &= pattern.CheckFilterEntity(Ident,
							filter.name, filterEntity);
				}
				if(filter.entities.Count != 1)
				{
					Ident.ReportError("The filter " + filterNameWithEntitySuffix + " must be declared with exactly one variable, but is declared with "
							+ filter.entities.Count + " variables"
							+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
					allFilterEntitiesExistAndAreOfAdmissibleType = false;
				}
				return allFilterEntitiesExistAndAreOfAdmissibleType;
			}
			case "keepOneForEachAccumulateBy":
				if(filter.entities.Count != 3)
				{
					Ident.ReportError("The filter " + filter.FilterName
							+ " must be declared with exactly one variable, one accumulation variable,"
							+ " and one accumulation method, but is declared with " + filter.entities.Count + " entities"
							+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
					return false;
				}
				else
				{
					if(filter.entities[0].Equals(filter.entities[1]))
					{
						Ident.ReportError("The accumulation variable"
								+ " must be different from the variable " + filter.entities[0]
								+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
						return false;
					}
					bool filterEntityExistsAndIsOfAdmissibleType = pattern.CheckFilterEntity(Ident,
							filterNameWithEntitySuffix, filter.entities[0]);
					if(!filterEntityExistsAndIsOfAdmissibleType)
						return false;
					ArrayAccumulationMethodNode accumulationMethod =
							ArrayAccumulationMethodNode.GetArrayMethodNode(filter.entities[2]);
					if(accumulationMethod == null)
					{
						Ident.ReportError("The array accumulation method "
								+ filter.entities[2] + " is not known"
								+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
						return false;
					}
					VarDeclNode filterAccumulationVariable = TryGetVar(filter.entities[1]);
					if(filterAccumulationVariable == null)
					{
						Ident.ReportError("Unknown accumulation variable " + filter.entities[1]
								+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
						return false;
					}
					TypeNode filterAccumulationVariableType = filterAccumulationVariable.DeclType;
					if(!accumulationMethod.IsValidTargetTypeOfAccumulation(filterAccumulationVariableType))
					{
						Ident.ReportError("The array accumulation method " + filter.entities[2]
								+ " is not applicable to the type " + filterAccumulationVariableType.TypeName
								+ " of the accumulation variable " + filter.entities[1]
								+ " / its result cannot be assigned to the accumulation variable."
								+ " (Allowed are: " + accumulationMethod.ValidTargetTypesOfAccumulation + ")"
								+ " (in " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ").");
						return false;
					}
					return true;
				}
			default:
				Debug.Assert((false));
				return false;
			}
		}

		public virtual NodeDeclNode TryGetNode(string name)
		{
			return pattern.TryGetNode(name);
		}

		public virtual EdgeDeclNode TryGetEdge(string name)
		{
			return pattern.TryGetEdge(name);
		}

		public virtual VarDeclNode TryGetVar(string name)
		{
			return pattern.TryGetVar(name);
		}

		public override DeclNode TryGetMember(string name)
		{
			NodeDeclNode node = pattern.TryGetNode(name);
			if(node != null)
				return node;
			EdgeDeclNode edge = pattern.TryGetEdge(name);
			if(edge != null)
				return edge;
			return pattern.TryGetVar(name);
		}

		public virtual ISet<NodeDeclNode> Nodes
		{
			get
			{
				ISet<NodeDeclNode> nodes = new HashSet<NodeDeclNode>();
				foreach(NodeDeclNode node in pattern.Nodes)
				{
					if(!(node is DummyNodeDeclNode))
						nodes.Add(node);
				}
				return Collections.UnmodifiableSet(nodes);
			}
		}

		public virtual ISet<EdgeDeclNode> Edges
		{
			get
			{
				return pattern.Edges;
			}
		}

		public virtual ISet<VarDeclNode> Variables
		{
			get
			{
				ISet<VarDeclNode> vars = new HashSet<VarDeclNode>(pattern.DefVariablesToBeYieldedTo.ChildrenExact);
				foreach(DeclNode varCand in pattern.ParamDecls)
				{
					if(!(varCand is VarDeclNode))
						continue;
					VarDeclNode var = (VarDeclNode)varCand;
					vars.Add(var);
				}
				return Collections.UnmodifiableSet(vars);
			}
		}

		public override ISet<DeclNode> Entities
		{
			get
			{
				return pattern.Entities;
			}
		}

		/// <summary>
		/// Returns the IR object for this defined match type node. </summary>
		public virtual DefinedMatchType IRDefinedMatchType
		{
			get
			{
				return CheckIR(typeof(DefinedMatchType));
			}
		}

		protected internal override IR ConstructIR()
		{
			if(IsIRAlreadySet())
				return (DefinedMatchType)IR;

			PatternGraphLhs patternGraph = pattern.IRPatternGraphLhs;
			foreach(DeclNode varCand in pattern.ParamDecls)
			{
				if(!(varCand is VarDeclNode))
					continue;
				VarDeclNode var = (VarDeclNode)varCand;
				patternGraph.AddVariable(var.CheckIR(typeof(Variable)));
			}

			DefinedMatchType definedMatchType = new DefinedMatchType(Ident.ToString(), Ident.IRIdent,
					patternGraph);

			// mark this node as already visited
			IR = definedMatchType;

			// filters add themselves to the match type when their IR is constructed
			foreach(MatchClassFilterCharacter filter in filters)
			{
				if(filter is MatchClassFilterFunctionDeclNode)
					((MatchClassFilterFunctionDeclNode)filter).CheckIR(typeof(MatchClassFilterFunction));
				else
					((MatchClassFilterAutoGeneratedDeclNode)filter).CheckIR(typeof(MatchClassFilterAutoGenerated));
			}

			return definedMatchType;
		}
	}

}
