/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ir
{

using System.Collections.Generic;

using FilterAutoGenerated = de.unika.ipd.grgen.ir.executable.FilterAutoGenerated;
using FilterAutoSupplied = de.unika.ipd.grgen.ir.executable.FilterAutoSupplied;
using Rule = de.unika.ipd.grgen.ir.executable.Rule;
using Expression = de.unika.ipd.grgen.ir.expr.Expression;

public class FilterInvocation : FilterInvocationBase
{
	internal FilterAutoGenerated filterAutoGenerated;
	internal FilterAutoSupplied filterAutoSupplied;

	internal IList<Expression> filterArguments;

	public FilterInvocation(string name, Ident ident, FilterAutoGenerated filterAutoGenerated, Rule iteratedAction)
		: base(name, ident, iteratedAction)
	{
		this.filterAutoGenerated = filterAutoGenerated;
		this.filterArguments = new List<Expression>();
	}

	public FilterInvocation(string name, Ident ident, FilterAutoSupplied filterAutoSupplied, Rule iteratedAction)
		: base(name, ident, iteratedAction)
	{
		this.filterAutoSupplied = filterAutoSupplied;
		this.filterArguments = new List<Expression>();
	}

	public virtual void AddArgument(Expression expr)
	{
		filterArguments.Add(expr);
	}

	public virtual FilterAutoSupplied FilterAutoSupplied
	{
		get
		{
		return filterAutoSupplied;
		}
	}

	public virtual FilterAutoGenerated FilterAutoGenerated
	{
		get
		{
		return filterAutoGenerated;
		}
	}

	public virtual IList<Expression> FilterArguments
	{
		get
		{
		return filterArguments;
		}
	}

	public virtual Expression GetFilterArgument(int i)
	{
		return filterArguments[i];
	}
}

}
