/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author shack, Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ast.decl.executable
{

using System;
using System.Collections.Generic;

using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
using de.unika.ipd.grgen.ast;
using IdentNode = de.unika.ipd.grgen.ast.IdentNode;
using PackageIdentNode = de.unika.ipd.grgen.ast.PackageIdentNode;
using DeclNode = de.unika.ipd.grgen.ast.decl.DeclNode;
using ConstraintDeclNode = de.unika.ipd.grgen.ast.decl.pattern.ConstraintDeclNode;
using EdgeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.EdgeDeclNode;
using NodeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.NodeDeclNode;
using VarDeclNode = de.unika.ipd.grgen.ast.decl.pattern.VarDeclNode;
using DeclExprNode = de.unika.ipd.grgen.ast.expr.DeclExprNode;
using ExprNode = de.unika.ipd.grgen.ast.expr.ExprNode;
using EdgeTypeNode = de.unika.ipd.grgen.ast.model.type.EdgeTypeNode;
using InheritanceTypeNode = de.unika.ipd.grgen.ast.model.type.InheritanceTypeNode;
using NodeTypeNode = de.unika.ipd.grgen.ast.model.type.NodeTypeNode;
using PatternGraphLhsNode = de.unika.ipd.grgen.ast.pattern.PatternGraphLhsNode;
using DefinedMatchTypeNode = de.unika.ipd.grgen.ast.type.DefinedMatchTypeNode;
using TypeNode = de.unika.ipd.grgen.ast.type.TypeNode;
using de.unika.ipd.grgen.ast.util;
using de.unika.ipd.grgen.ast.util;
using FilterAutoGenerated = de.unika.ipd.grgen.ir.executable.FilterAutoGenerated;
using FilterAutoSupplied = de.unika.ipd.grgen.ir.executable.FilterAutoSupplied;
using MatchingAction = de.unika.ipd.grgen.ir.executable.MatchingAction;
using Expression = de.unika.ipd.grgen.ir.expr.Expression;

/// <summary>
/// base class for actions = tests + rules
/// </summary>
public abstract class ActionDeclNode : TopLevelMatcherDeclNode
{
	static ActionDeclNode()
	{
		SetClassName(typeof(ActionDeclNode), "action declaration");
	}

	protected internal CollectNode<BaseNode> returnFormalParametersUnresolved;
	public CollectNode<TypeNode> returnFormalParameters;
	protected internal List<FilterAutoDeclNode> filters;
	protected internal CollectNode<IdentNode> implementedMatchTypesUnresolved;
	protected internal CollectNode<DefinedMatchTypeNode> implementedMatchTypes;

	protected internal ActionDeclNode(IdentNode id, TypeNode type, PatternGraphLhsNode pattern,
			CollectNode<IdentNode> implementedMatchTypes, CollectNode<BaseNode> rets)
		: base(id, type, pattern)
	{
		this.returnFormalParametersUnresolved = rets;
		BecomeParent(this.returnFormalParametersUnresolved);
		implementedMatchTypesUnresolved = implementedMatchTypes;
		BecomeParent(implementedMatchTypesUnresolved);
		this.filters = new List<FilterAutoDeclNode>();
	}

	public virtual void AddFilters(List<FilterAutoDeclNode> filters)
	{
		this.filters.AddRange(filters);
	}

	/// <summary>
	/// returns children of this node </summary>
	public override ICollection<BaseNode> Children
	{
		get
		{
		IList<BaseNode> children = new List<BaseNode>();
		children.Add(ident);
		children.Add(GetValidVersionCollectNode(returnFormalParametersUnresolved, returnFormalParameters));
		children.Add(pattern);
		children.Add(GetValidVersionCollectNode(implementedMatchTypesUnresolved, implementedMatchTypes));
		return children;
		}
	}

	/// <summary>
	/// returns names of the children, same order as in getChildren </summary>
	public override ICollection<string> ChildrenNames
	{
		get
		{
		IList<string> childrenNames = new List<string>();
		childrenNames.Add("ident");
		childrenNames.Add("ret");
		childrenNames.Add("pattern");
		childrenNames.Add("implementedMatchTypes");
		return childrenNames;
		}
	}

	private static readonly CollectResolver<DefinedMatchTypeNode> matchTypeResolver =
			new CollectResolver<DefinedMatchTypeNode>(new DeclarationTypeResolver<DefinedMatchTypeNode>(typeof(DefinedMatchTypeNode)));
	private static readonly CollectResolver<TypeNode> retTypeResolver =
			new CollectResolver<TypeNode>(new DeclarationTypeResolver<TypeNode>(typeof(TypeNode)));

	/// <seealso cref="de.unika.ipd.grgen.ast.BaseNode.resolveLocal() "/>
	protected internal override bool ResolveLocal()
	{
		foreach(IdentNode mtid in implementedMatchTypesUnresolved.ChildrenExact)
		{
			if(!(mtid is PackageIdentNode))
				FixupDefinition(mtid, mtid.Scope);
		}
		implementedMatchTypes = matchTypeResolver.Resolve(implementedMatchTypesUnresolved, this);
		returnFormalParameters = retTypeResolver.Resolve(returnFormalParametersUnresolved, this);

		return returnFormalParameters != null
				& implementedMatchTypes != null
				& ResolveFilters(filters);
	}

	/// <summary>
	/// Check if actual return arguments are conformant to the formal return parameters.
	/// </summary>
	protected internal virtual bool CheckReturns(CollectNode<ExprNode> returnArgs)
	{
		bool res = true;

		int declaredNumRets = returnFormalParameters.Size();
		int actualNumRets = returnArgs.Size();
		for(int i = 0; i < Math.Min(declaredNumRets, actualNumRets); i++)
		{
			ExprNode retExpr = returnArgs.Get(i);
			TypeNode retDeclType = returnFormalParameters.Get(i);

			res &= CheckReturns(i, retExpr, retDeclType);
		}

		//check the number of returned elements
		if(actualNumRets != declaredNumRets)
		{
			res = false;
			if(declaredNumRets == 0)
			{
				returnArgs.ReportError("No return parameters are declared in " + Kind + " " + ident +
						", but " + actualNumRets + " return arguments are given.");
			}
			else if(actualNumRets == 0)
			{
				ReportError("A return statement is missing in " + Kind + " " + ident +
						", which is declared with " + declaredNumRets + " return parameters.");
			}
			else
			{
				returnArgs.ReportError("The return statement in " + Kind + " " + ident + " has a wrong number of arguments,"
						+ " given are " + actualNumRets + " arguments," + " but declared are " + declaredNumRets + " parameters.");
			}
		}

		return res;
	}

	private bool CheckReturns(int i, ExprNode retExpr, TypeNode retDeclType)
	{
		bool res = true;

		TypeNode retExprType = retExpr.Type;
		TypeNode retParameterType = returnFormalParameters.Get(i);

		if(!retExprType.IsCompatibleTo(retDeclType))
		{
			res = false;
			string exprTypeName = retExprType.TypeName;
			string parameterTypeName = retParameterType.TypeName;
			ident.ReportError("Cannot convert " + (i + 1) + ". return argument"
					+ " from " + exprTypeName + " to the expected " + parameterTypeName
					+ " (in " + Kind + " " + ident + ")"
					+ retExprType.ToStringWithDeclarationCoordsIfCoordsAreOfInterest()
					+ retParameterType.ToStringWithDeclarationCoordsIfCoordsAreOfInterest()
					+ ".");
			return res;
		}

		if(!(retExpr is DeclExprNode))
			return res;
		ConstraintDeclNode retElem = ((DeclExprNode)retExpr).ConstraintDecl;
		if(retElem == null)
			return res;

		InheritanceTypeNode declaredRetType = retElem.DeclInhType;

		ISet<ConstraintDeclNode> homSet;
		if(retElem is NodeDeclNode)
			homSet = new LinkedHashSet<ConstraintDeclNode>(pattern.GetHomomorphic((NodeDeclNode)retElem));
		else
			homSet = new LinkedHashSet<ConstraintDeclNode>(pattern.GetHomomorphic((EdgeDeclNode)retElem));

		foreach(ConstraintDeclNode homElem in homSet)
		{
			if(homElem == retElem)
				continue;

			ConstraintDeclNode retypedElem = homElem.RetypedElement;
			if(retypedElem == null)
				continue;

			InheritanceTypeNode retypedElemType = retypedElem.DeclInhType;
			if(retypedElemType.IsA(declaredRetType))
				continue;

			res = false;
			retExpr.ReportError("Return argument " + retElem.Ident + " is homomorphic to "
					+ homElem.Ident + ", which gets retyped to the incompatible type "
					+ retypedElemType.ToStringWithDeclarationCoords() + " (in " + Kind + " " + ident + ").");
			return res;
		}

		return res;
	}

	protected internal override bool CheckLocal()
	{
		return CheckLeft()
				& CheckFilters(pattern, filters)
				& CheckMatchTypesImplemented();
	}

	public virtual bool CheckMatchTypesImplemented()
	{
		bool isOk = true;

		foreach(DefinedMatchTypeNode matchType in implementedMatchTypes.ChildrenExact)
			isOk &= CheckMatchTypeImplemented(matchType);

		return isOk;
	}

	public virtual bool CheckMatchTypeImplemented(DefinedMatchTypeNode matchType)
	{
		bool isOk = true;

		Dictionary<string, NodeDeclNode> knownNodes = new Dictionary<string, NodeDeclNode>();
		foreach(NodeDeclNode node in pattern.Nodes)
			knownNodes[node.Ident.ToString()] = node;
		foreach(NodeDeclNode node in matchType.Nodes)
			isOk = CheckNodeImplemented(node, matchType, knownNodes);

		Dictionary<string, EdgeDeclNode> knownEdges = new Dictionary<string, EdgeDeclNode>();
		foreach(EdgeDeclNode edge in pattern.Edges)
			knownEdges[edge.Ident.ToString()] = edge;
		foreach(EdgeDeclNode edge in matchType.Edges)
			isOk = CheckEdgeImplemented(edge, matchType, knownEdges);

		Dictionary<string, VarDeclNode> knownVariables = new Dictionary<string, VarDeclNode>();
		foreach(VarDeclNode var in pattern.DefVariablesToBeYieldedTo.ChildrenExact)
			knownVariables[var.Ident.ToString()] = var;
		foreach(DeclNode varCand in pattern.ParamDecls)
		{
			if(!(varCand is VarDeclNode))
				continue;
			VarDeclNode var = (VarDeclNode)varCand;
			knownVariables[var.Ident.ToString()] = var;
		}
		foreach(VarDeclNode var in matchType.Variables)
			isOk = CheckVariableImplemented(var, matchType, knownVariables);

		return isOk;
	}

	private bool CheckNodeImplemented(NodeDeclNode node, DefinedMatchTypeNode matchType,
			Dictionary<string, NodeDeclNode> knownNodes)
	{
		bool isOk = true;

		string actionName = Kind + " " + Ident.ToString();
		string matchTypeName = matchType.Ident.ToString() + matchType.Decl.GetDeclarationCoords();
		string nodeName = node.Ident.ToString();
		if(!knownNodes.ContainsKey(nodeName))
		{
			Ident.ReportError("The " + actionName + " does not implement the node " + nodeName
					+ " expected from the match class " + matchTypeName + ".");
			isOk = false;
		}
		else
		{
			NodeDeclNode nodeFromPattern = knownNodes[nodeName];
			NodeTypeNode type = node.DeclNodeType;
			NodeTypeNode typeOfNodeFromPattern = nodeFromPattern.DeclNodeType;
			if(!type.IsEqual(typeOfNodeFromPattern))
			{
				Ident.ReportError("The type of the node " + nodeName + " from the " + actionName
						+ " does not equal the type of the node from the match class " + matchTypeName + "."
						+ " In the match class, " + type.TypeName + " is declared, but in the pattern, "
						+ typeOfNodeFromPattern.TypeName + " is declared.");
				isOk = false;
			}
			if(nodeFromPattern.defEntityToBeYieldedTo && !node.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The node " + nodeName + " from the " + actionName
						+ " is a def node, while it is a node in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
			if(!nodeFromPattern.defEntityToBeYieldedTo && node.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The node " + nodeName + " from the " + actionName
						+ " is a node, while it is a def node in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
		}

		return isOk;
	}

	private bool CheckEdgeImplemented(EdgeDeclNode edge, DefinedMatchTypeNode matchType,
			Dictionary<string, EdgeDeclNode> knownEdges)
	{
		bool isOk = true;

		string actionName = Kind + " " + Ident.ToString();
		string matchTypeName = matchType.Ident.ToString() + matchType.Decl.GetDeclarationCoords();
		string edgeName = edge.Ident.ToString();
		if(!knownEdges.ContainsKey(edgeName))
		{
			Ident.ReportError("The " + actionName + " does not implement the edge " + edgeName
					+ " expected from the match class " + matchTypeName + ".");
			isOk = false;
		}
		else
		{
			EdgeDeclNode edgeFromPattern = knownEdges[edgeName];
			EdgeTypeNode type = edge.DeclEdgeType;
			EdgeTypeNode typeOfEdgeFromPattern = edgeFromPattern.DeclEdgeType;
			if(!type.IsEqual(typeOfEdgeFromPattern))
			{
				Ident.ReportError("The type of the edge " + edgeName + " from the " + actionName
						+ " does not equal the type of the edge from the match class " + matchTypeName + "."
						+ " In the match class, " + type.TypeName + " is declared, but in the pattern, "
						+ typeOfEdgeFromPattern.TypeName + " is declared.");
				isOk = false;
			}
			if(edgeFromPattern.defEntityToBeYieldedTo && !edge.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The edge " + edgeName + " from the " + actionName
						+ " is a def edge, while it is an edge in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
			if(!edgeFromPattern.defEntityToBeYieldedTo && edge.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The edge " + edgeName + " from the " + actionName
						+ " is an edge, while it is a def edge in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
		}

		return isOk;
	}

	private bool CheckVariableImplemented(VarDeclNode var, DefinedMatchTypeNode matchType,
			Dictionary<string, VarDeclNode> knownVariables)
	{
		bool isOk = true;

		string actionName = Kind + " " + Ident.ToString();
		string matchTypeName = matchType.Ident.ToString() + matchType.Decl.GetDeclarationCoords();
		string varName = var.Ident.ToString();
		if(!knownVariables.ContainsKey(varName))
		{
			Ident.ReportError("The " + actionName + " does not implement the variable " + varName
					+ " expected from the match class " + matchTypeName + ".");
			isOk = false;
		}
		else
		{
			VarDeclNode varFromPattern = knownVariables[varName];
			TypeNode type = var.DeclType;
			TypeNode typeOfVarFromPattern = varFromPattern.DeclType;
			if(!type.IsEqual(typeOfVarFromPattern))
			{
				Ident.ReportError("The type of the variable " + varName + " from the " + actionName
						+ " does not equal the type of the variable from the match class " + matchTypeName
						+ "." + " In the match class, " + type.TypeName + " is declared, but in the pattern, "
						+ typeOfVarFromPattern.TypeName + " is declared.");
				isOk = false;
			}
			if(varFromPattern.defEntityToBeYieldedTo && !var.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The variable " + varName + " from the " + actionName
						+ " is a def variable, while it is a variable in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
			if(!varFromPattern.defEntityToBeYieldedTo && var.defEntityToBeYieldedTo)
			{
				Ident.ReportError("The variable " + varName + " from the " + actionName
						+" is a variable, while it is a def variable in the match class "
						+ matchTypeName + ".");
				isOk = false;
			}
		}

		return isOk;
	}

	public virtual ICollection<DefinedMatchTypeNode> ImplementedMatchClasses
	{
		get
		{
		return implementedMatchTypes.ChildrenExact;
		}
	}

	protected internal virtual void ConstructIRaux(MatchingAction constructedMatchingAction, CollectNode<ExprNode> aReturns)
	{
		// add Params to the IR
		AddParams(constructedMatchingAction);

		// add Return-Params to the IR
		foreach(ExprNode aReturnAST in aReturns.ChildrenExact)
		{
			ExprNode evaluatedReturn = aReturnAST.Evaluate();
			Expression aReturn = evaluatedReturn.CheckIR(typeof(Expression));
			// actual return-parameter
			constructedMatchingAction.AddReturn(aReturn);
		}

		// filters add themselves to the rule when their IR is constructed
		foreach(FilterAutoDeclNode filter in filters)
		{
			if(filter is FilterAutoSuppliedDeclNode)
				((FilterAutoSuppliedDeclNode)filter).CheckIR(typeof(FilterAutoSupplied));
			else
				((FilterAutoGeneratedDeclNode)filter).CheckIR(typeof(FilterAutoGenerated));
		}
	}

	public static string KindStr
	{
		get
		{
		return "action";
		}
	}
}

}
