/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ast.decl.executable
{

using System.Collections.Generic;
using System.Text;

using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
using IdentNode = de.unika.ipd.grgen.ast.IdentNode;
using MatchClassFilterCharacter = de.unika.ipd.grgen.ast.MatchClassFilterCharacter;
using PackageIdentNode = de.unika.ipd.grgen.ast.PackageIdentNode;
using DeclNode = de.unika.ipd.grgen.ast.decl.DeclNode;
using DefinedMatchTypeNode = de.unika.ipd.grgen.ast.type.DefinedMatchTypeNode;
using TypeNode = de.unika.ipd.grgen.ast.type.TypeNode;
using de.unika.ipd.grgen.ast.util;
using IR = de.unika.ipd.grgen.ir.IR;
using MatchClassFilterAutoGenerated = de.unika.ipd.grgen.ir.executable.MatchClassFilterAutoGenerated;
using DefinedMatchType = de.unika.ipd.grgen.ir.type.DefinedMatchType;

/// <summary>
/// AST node class representing declarations of auto-generated match class filter functions
/// </summary>
public class MatchClassFilterAutoGeneratedDeclNode : FilterAutoDeclNode, MatchClassFilterCharacter
{
	static MatchClassFilterAutoGeneratedDeclNode()
	{
		SetClassName(typeof(MatchClassFilterAutoGeneratedDeclNode), "match filter function declaration");
	}

	public string name;
	public List<string> entities; // null for auto, otherwise list with at least one element
	protected internal List<TypeNode> entityTypes;

	protected internal IdentNode matchTypeUnresolved;
	protected internal DefinedMatchTypeNode matchType;

	public MatchClassFilterAutoGeneratedDeclNode(IdentNode ident, string name, List<string> entities,
			IdentNode matchType)
		: base(ident)
	{
		this.name = name;
		this.entities = entities;
		this.matchTypeUnresolved = matchType;
	}

	/// <summary>
	/// returns children of this node </summary>
	public override ICollection<BaseNode> Children
	{
		get
		{
			IList<BaseNode> children = new List<BaseNode>();
			children.Add(matchTypeUnresolved);
			return children;
		}
	}

	/// <summary>
	/// returns names of the children, same order as in getChildren </summary>
	public override ICollection<string> ChildrenNames
	{
		get
		{
			IList<string> childrenNames = new List<string>();
			childrenNames.Add("matchType");
			return childrenNames;
		}
	}

	private static readonly DeclarationTypeResolver<DefinedMatchTypeNode> matchTypeResolver =
			new DeclarationTypeResolver<DefinedMatchTypeNode>(typeof(DefinedMatchTypeNode));

	/// <seealso cref="de.unika.ipd.grgen.ast.BaseNode.resolveLocal() "/>
	protected internal override bool ResolveLocal()
	{
		if(!(matchTypeUnresolved is PackageIdentNode))
			FixupDefinition(matchTypeUnresolved, matchTypeUnresolved.Scope);
		matchType = matchTypeResolver.Resolve(matchTypeUnresolved, this);
		return matchType != null;
	}

	/// <seealso cref="de.unika.ipd.grgen.ast.BaseNode.resolveLocal() "/>
	protected internal override bool CheckLocal()
	{
		if(entities == null)
		{
			if(!name.Equals("auto"))
			{
				ReportError("Unknown auto-generated filter " + name + " (only auto comes without parameters).");
				return false;
			}
			return true;
		}
		else
		{
			entityTypes = new List<TypeNode>();
			for(int i = 0; i < entities.Count; ++i)
			{
				if(name.Equals("keepOneForEachAccumulateBy") && i == entities.Count - 1)
					continue;

				string entity = entities[i];
				DeclNode resolvedEntity = matchType.TryGetMember(entity);
				if(resolvedEntity == null)
				{
					ReportError("The entity " + entity
							+ " referenced in the filter declaration " + FilterNameWithEntitySuffix
							+ " is not known in the "
							+ "match class " + matchType.Ident + ".");
					return false;
				}
				entityTypes.Add(resolvedEntity.DeclType);
			}
		}
		return true;
	}

	public virtual string FilterName
	{
		get
		{
			return name;
		}
	}

	public virtual string FilterNameWithEntitySuffix
	{
		get
		{
			StringBuilder sb = new StringBuilder();
			sb.Append(name);
			if(entities != null && entities.Count > 0)
			{
				sb.Append("<");
				bool first = true;
				foreach(string entity in entities)
				{
					if(first)
						first = false;
					else
						sb.Append(",");
					sb.Append(entity);
				}
				sb.Append(">");
			}
			return sb.ToString();
		}
	}

	public virtual DefinedMatchTypeNode MatchType
	{
		get
		{
			return matchType;
		}
	}

	/// <summary>
	/// Returns the IR object for this autogen filter node. </summary>
	public virtual MatchClassFilterAutoGenerated IRMatchClassFilterAutoGenerated
	{
		get
		{
			return CheckIR(typeof(MatchClassFilterAutoGenerated));
		}
	}

	protected internal override IR ConstructIR()
	{
		// return if the IR object was already constructed
		// that may happen in recursive calls
		if(IsIRAlreadySet())
			return IR;

		MatchClassFilterAutoGenerated filterAutoGen = new MatchClassFilterAutoGenerated(name, entities);

		// mark this node as already visited
		IR = filterAutoGen;

		DefinedMatchType definedMatchType = matchType.CheckIR(typeof(DefinedMatchType));
		filterAutoGen.MatchClass = definedMatchType;
		definedMatchType.AddMatchClassFilter(filterAutoGen);

		if(entityTypes != null)
		{
			foreach(TypeNode entityType in entityTypes)
				filterAutoGen.AddEntityType(entityType.IRType);
		}

		return filterAutoGen;
	}
}

}
