/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author shack
/// </summary>

namespace de.unika.ipd.grgen.ast.decl.executable
{
	using System;
	using System.Collections.Generic;
	using System.Diagnostics;

	using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
	using CallActionNode = de.unika.ipd.grgen.ast.CallActionNode;
	using ExecNode = de.unika.ipd.grgen.ast.ExecNode;
	using IdentNode = de.unika.ipd.grgen.ast.IdentNode;
	using DeclNode = de.unika.ipd.grgen.ast.decl.DeclNode;
	using AlternativeCaseDeclNode = de.unika.ipd.grgen.ast.decl.pattern.AlternativeCaseDeclNode;
	using AlternativeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.AlternativeDeclNode;
	using ConstraintDeclNode = de.unika.ipd.grgen.ast.decl.pattern.ConstraintDeclNode;
	using EdgeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.EdgeDeclNode;
	using EdgeTypeChangeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.EdgeTypeChangeDeclNode;
	using IteratedDeclNode = de.unika.ipd.grgen.ast.decl.pattern.IteratedDeclNode;
	using NodeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.NodeDeclNode;
	using NodeTypeChangeDeclNode = de.unika.ipd.grgen.ast.decl.pattern.NodeTypeChangeDeclNode;
	using RhsDeclNode = de.unika.ipd.grgen.ast.decl.pattern.RhsDeclNode;
	using VarDeclNode = de.unika.ipd.grgen.ast.decl.pattern.VarDeclNode;
	using ExprNode = de.unika.ipd.grgen.ast.expr.ExprNode;
	using ArrayAccumulationMethodNode = de.unika.ipd.grgen.ast.expr.array.ArrayAccumulationMethodNode;
	using ConnectionCharacter = de.unika.ipd.grgen.ast.pattern.ConnectionCharacter;
	using ConnectionNode = de.unika.ipd.grgen.ast.pattern.ConnectionNode;
	using ImplicitNegComputer = de.unika.ipd.grgen.ast.pattern.ImplicitNegComputer;
	using ImplicitNegComputerInduced = de.unika.ipd.grgen.ast.pattern.ImplicitNegComputerInduced;
	using PatternGraphLhsNode = de.unika.ipd.grgen.ast.pattern.PatternGraphLhsNode;
	using TypeNode = de.unika.ipd.grgen.ast.type.TypeNode;
	using Entity = de.unika.ipd.grgen.ir.Entity;
	using MatchingAction = de.unika.ipd.grgen.ir.executable.MatchingAction;
	using Rule = de.unika.ipd.grgen.ir.executable.Rule;
	using Alternative = de.unika.ipd.grgen.ir.pattern.Alternative;
	using Node = de.unika.ipd.grgen.ir.pattern.Node;
	using PatternGraphLhs = de.unika.ipd.grgen.ir.pattern.PatternGraphLhs;
	using PatternGraphRhs = de.unika.ipd.grgen.ir.pattern.PatternGraphRhs;
	using Variable = de.unika.ipd.grgen.ir.pattern.Variable;
	using de.unika.ipd.grgen.util.collection;


	/// <summary>
	/// Base class for pattern matching related ast nodes
	/// </summary>
	public abstract class MatcherDeclNode : DeclNode
	{
		public PatternGraphLhsNode pattern;

		public MatcherDeclNode(IdentNode id, TypeNode type, PatternGraphLhsNode left)
			: base(id, type)
		{

			this.pattern = left;
			BecomeParent(this.pattern);
		}

		/// <summary>
		/// Get the IR object for this matcher decl node.
		/// The IR object is instance of Rule. </summary>
		/// <returns> The IR object. </returns>
		public virtual Rule IRMatcher
		{
			get
			{
				return CheckIR<Rule>(typeof(Rule));
			}
		}

		protected internal static bool ResolveFilters(List<FilterAutoDeclNode> filters)
		{
			bool filtersOk = true;
			foreach(FilterAutoDeclNode filter in filters)
			{
				if(filter is FilterAutoSuppliedDeclNode)
					filtersOk &= ((FilterAutoSuppliedDeclNode)filter).Resolve();
				else
					filtersOk &= ((FilterAutoGeneratedDeclNode)filter).Resolve();
			}
			return filtersOk;
		}

		protected internal virtual bool CheckFilters(PatternGraphLhsNode pattern, List<FilterAutoDeclNode> filters)
		{
			bool filtersOk = true;
			foreach(FilterAutoDeclNode filter in filters)
			{
				if(filter is FilterAutoSuppliedDeclNode)
					filtersOk &= ((FilterAutoSuppliedDeclNode)filter).Check();
				else
					filtersOk &= ((FilterAutoGeneratedDeclNode)filter).Check();
			}
			bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
			HashSet<string> alreadySeenFilters = new HashSet<string>();
			foreach(FilterAutoDeclNode filter in filters)
			{
				if(filter is FilterAutoGeneratedDeclNode)
				{
					FilterAutoGeneratedDeclNode filterAutoGenerated = (FilterAutoGeneratedDeclNode)filter;
					string filterNameWithEntitySuffix = filterAutoGenerated.FilterNameWithEntitySuffix;
					if(alreadySeenFilters.Contains(filterNameWithEntitySuffix))
					{
						ReportError("The filter " + filterNameWithEntitySuffix + " was already declared for " + pattern.nameOfGraph
								+ ", only one declaration is admissible.");
						allFilterEntitiesExistAndAreOfAdmissibleType = false;
					}
					else
						alreadySeenFilters.Add(filterNameWithEntitySuffix);
					allFilterEntitiesExistAndAreOfAdmissibleType &= CheckAutoGeneratedFilter(filterAutoGenerated);
				}
			}
			return filtersOk & allFilterEntitiesExistAndAreOfAdmissibleType;
		}

		protected internal virtual bool CheckAutoGeneratedFilter(FilterAutoGeneratedDeclNode filter)
		{
			string filterNameWithEntitySuffix = filter.FilterNameWithEntitySuffix;
			switch(filter.name)
			{
			case "orderAscendingBy":
			case "orderDescendingBy":
			{
				bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
				foreach(string filterEntity in filter.entities)
				{
					allFilterEntitiesExistAndAreOfAdmissibleType &= pattern.CheckFilterVariable(Ident,
							filterNameWithEntitySuffix, filterEntity);
				}
				return allFilterEntitiesExistAndAreOfAdmissibleType;
			}
			case "keepOneForEach":
			case "groupBy":
			case "keepSameAsFirst":
			case "keepSameAsLast":
			{
				bool allFilterEntitiesExistAndAreOfAdmissibleType = true;
				foreach(string filterEntity in filter.entities)
				{
					allFilterEntitiesExistAndAreOfAdmissibleType &= pattern.CheckFilterEntity(Ident,
							filterNameWithEntitySuffix, filterEntity);
				}
				if(filter.entities.Count != 1)
				{
					ReportError("The filter " + filter.FilterName
							+ " must be declared with exactly one variable, but is declared with "
							+ filter.entities.Count + " variables"
							+ FilterSpecification(filterNameWithEntitySuffix) + ".");
					allFilterEntitiesExistAndAreOfAdmissibleType = false;
				}
				return allFilterEntitiesExistAndAreOfAdmissibleType;
			}
			case "keepOneForEachAccumulateBy":
				if(filter.entities.Count != 3)
				{
					Ident.ReportError("The filter " + filter.FilterName
							+ " must be declared with exactly one variable, one accumulation variable,"
							+ " and one accumulation method, but is declared with " + filter.entities.Count + " entities"
							+ FilterSpecification(filterNameWithEntitySuffix) + ".");
					return false;
				}
				else
				{
					if(filter.entities[0].Equals(filter.entities[1]))
					{
						Ident.ReportError("The accumulation variable"
								+ " must be different from the variable " + filter.entities[0]
								+ FilterSpecification(filterNameWithEntitySuffix) + ".");
						return false;
					}
					bool filterEntityExistsAndIsOfAdmissibleType = pattern.CheckFilterEntity(Ident,
							filterNameWithEntitySuffix, filter.entities[0]);
					if(!filterEntityExistsAndIsOfAdmissibleType)
						return false;
					ArrayAccumulationMethodNode accumulationMethod =
							ArrayAccumulationMethodNode.GetArrayMethodNode(filter.entities[2]);
					if(accumulationMethod == null)
					{
						Ident.ReportError("The array accumulation method "
								+ filter.entities[2] + " is not known"
								+ FilterSpecification(filterNameWithEntitySuffix) + ".");
						return false;
					}
					VarDeclNode filterAccumulationVariable = pattern.TryGetVar(filter.entities[1]);
					if(filterAccumulationVariable == null)
					{
						Ident.ReportError("Unknown accumulation variable " + filter.entities[1]
								+ FilterSpecification(filterNameWithEntitySuffix) + ".");
						return false;
					}
					TypeNode filterAccumulationVariableType = filterAccumulationVariable.DeclType;
					if(!accumulationMethod.IsValidTargetTypeOfAccumulation(filterAccumulationVariableType))
					{
						Ident.ReportError("The array accumulation method " + filter.entities[2]
								+ " is not applicable to the type " + filterAccumulationVariableType.TypeName
								+ " of the accumulation variable " + filter.entities[1]
								+ " / its result cannot be assigned to the accumulation variable."
								+ " (Allowed are: " + accumulationMethod.ValidTargetTypesOfAccumulation + ")"
								+ FilterSpecification(filterNameWithEntitySuffix) + ".");
						return false;
					}
					return true;
				}
			case "auto":
				return true; // skip
			default:
				Debug.Assert((false));
				return false;
			}
		}

		private string FilterSpecification(string filterNameWithEntitySuffix)
		{
			return " (in filter " + filterNameWithEntitySuffix + " for " + pattern.nameOfGraph + ")";
		}

		protected internal virtual bool CheckNonAction(RhsDeclNode right)
		{
			bool leftHandGraphsOk = CheckLeft();

			bool rightHandGraphsOk = true;
			if(right != null)
				rightHandGraphsOk = right.CheckAgainstLhsPattern(pattern);

			bool noReturnInPattern = true;
			if(pattern.returns.Size() > 0)
			{
				ReportError("A return statement is not allowed in a " + Kind + ".");
				noReturnInPattern = false;
			}

			bool noReturnInNestedReplacement = true;
			if(right != null)
			{
				if(right.patternGraph.returns.Size() > 0)
				{
					ReportError("A return statement is not allowed in a " + Kind + ".");
					noReturnInNestedReplacement = false;
				}
			}

			bool rhsReuseOk = true;
			bool execParamsNotDeleted = true;
			bool sameNumberOfRewriteParts = SameNumberOfRewriteParts(right, Kind);
			bool noNestedRewriteParameters = true;
			if(right != null)
			{
				rhsReuseOk = CheckRhsReuse(right);
				execParamsNotDeleted = CheckExecParamsNotDeleted(right);
				noNestedRewriteParameters = NoNestedRewriteParameters(right, Kind);
			}

			return leftHandGraphsOk
					& rightHandGraphsOk
					& sameNumberOfRewriteParts
					& noNestedRewriteParameters
					& rhsReuseOk
					& noReturnInPattern
					& noReturnInNestedReplacement
					& execParamsNotDeleted;
		}

		protected internal virtual bool CheckLeft()
		{
			// check if reused names of edges connect the same nodes in the same direction with the same edge kind for each usage
			bool isLhsEdgeReuseOk = true;

			// get the negative and independent graphs and the pattern of this ActionDeclNode
			// NOTE: the order affect the error coords
			ICollection<PatternGraphLhsNode> leftHandGraphs = new List<PatternGraphLhsNode>();
			leftHandGraphs.Add(pattern);
			foreach(PatternGraphLhsNode negative in pattern.negs.ChildrenExact)
				leftHandGraphs.Add(negative);
			foreach(PatternGraphLhsNode independent in pattern.idpts.ChildrenExact)
				leftHandGraphs.Add(independent);

			PatternGraphLhsNode[] graphs = new PatternGraphLhsNode[leftHandGraphs.Count];
			leftHandGraphs.CopyTo(graphs, 0);
			ICollection<EdgeDeclNode> alreadyReported = new HashSet<EdgeDeclNode>();

			for(int i = 0; i < graphs.Length; i++)
			{
				foreach(ConnectionCharacter connectionCharacter in graphs[i].Connections)
				{
					if(!(connectionCharacter is ConnectionNode))
						continue;
					ConnectionNode connection = (ConnectionNode)connectionCharacter;

					for(int j = i + 1; j < graphs.Length; j++)
					{
						foreach(ConnectionCharacter nestedConnectionCharacter in graphs[j].Connections)
						{
							if(!(nestedConnectionCharacter is ConnectionNode))
								continue;
							ConnectionNode nestedConnection = (ConnectionNode)nestedConnectionCharacter;

							if(connection.Edge.Equals(nestedConnection.Edge) && !alreadyReported.Contains(connection.Edge))
								isLhsEdgeReuseOk &= IsLhsEdgeReuseOk(alreadyReported, connection, nestedConnection);
						}
					}
				}
			}

			return isLhsEdgeReuseOk;
		}

		private static bool IsLhsEdgeReuseOk(ICollection<EdgeDeclNode> alreadyReported,
				ConnectionNode connection, ConnectionNode nestedConnection)
		{
			bool edgeReuse = true;

			NodeDeclNode source = connection.Src;
			NodeDeclNode target = connection.Tgt;
			NodeDeclNode nestedSource = nestedConnection.Src;
			NodeDeclNode nestedTarget = nestedConnection.Tgt;

			Debug.Assert(!(source is NodeTypeChangeDeclNode), "no type changes in test actions");
			Debug.Assert(!(target is NodeTypeChangeDeclNode), "no type changes in test actions");
			Debug.Assert(!(nestedSource is NodeTypeChangeDeclNode), "no type changes in test actions");
			Debug.Assert(!(nestedTarget is NodeTypeChangeDeclNode), "no type changes in test actions");

			//check only if there's no dangling edge
			if(!( (source is NodeDeclNode) && ((NodeDeclNode)source).IsDummy() )
				&& !( (nestedSource is NodeDeclNode) && ((NodeDeclNode)nestedSource).IsDummy() )
				&& source != nestedSource)
			{
				alreadyReported.Add(connection.Edge);
				nestedConnection.ReportError("Reused edge " + connection.Edge
						+ " does not connect the same source nodes"
						+ DiffersFromSpecification(source, nestedSource, true) + ".");
				edgeReuse = false;
			}
			if(!( (target is NodeDeclNode) && ((NodeDeclNode)target).IsDummy() )
				&& !( (nestedTarget is NodeDeclNode) && ((NodeDeclNode)nestedTarget).IsDummy() )
				&& target != nestedTarget
				&& !alreadyReported.Contains(connection.Edge))
			{
				alreadyReported.Add(connection.Edge);
				nestedConnection.ReportError("Reused edge " + connection.Edge
						+ " does not connect the same target nodes"
						+ DiffersFromSpecification(target, nestedTarget, true) + ".");
				edgeReuse = false;
			}

			if(connection.ConnectionKind != nestedConnection.ConnectionKind)
			{
				alreadyReported.Add(connection.Edge);
				nestedConnection.ReportError("Reused edge " + connection.Edge
						+ " does not have the same connection kind"
						+ " (" + ConnectionNode.toString(connection.ConnectionKind) + " differs from nested " + ConnectionNode.toString(nestedConnection.ConnectionKind) + ").");
				edgeReuse = false;
			}

			return edgeReuse;
		}

		private static string DiffersFromSpecification(NodeDeclNode leftNode, NodeDeclNode rightNode, bool nested)
		{
			return " (" + leftNode.UserFriendlyToString()
					+ " differs from " + (nested ? "nested " : "")
					+ rightNode.UserFriendlyToString() + ")";
		}

		/// <summary>
		/// Checks, whether the reused nodes and edges of the RHS are consistent with the LHS.
		/// If consistent, replace the dummy nodes with the nodes the pattern edge is
		/// incident to (if these aren't dummy nodes themselves, of course). 
		/// </summary>
		protected internal virtual bool CheckRhsReuse(RhsDeclNode right)
		{
			bool res = true;

			Dictionary<EdgeDeclNode, NodeDeclNode> redirectedFrom = new Dictionary<EdgeDeclNode, NodeDeclNode>();
			Dictionary<EdgeDeclNode, NodeDeclNode> redirectedTo = new Dictionary<EdgeDeclNode, NodeDeclNode>();

			ICollection<EdgeDeclNode> alreadyReported = new HashSet<EdgeDeclNode>();
			foreach(ConnectionNode rightConnection in right.GetConnectionsToReuse(pattern))
			{
				EdgeDeclNode rightEdge = rightConnection.Edge;

				if(rightEdge is EdgeTypeChangeDeclNode)
					rightEdge = ((EdgeTypeChangeDeclNode)rightEdge).OldEdge;

				foreach(ConnectionCharacter leftConnectionCharacter in pattern.Connections)
				{
					if(!(leftConnectionCharacter is ConnectionNode))
						continue;

					ConnectionNode leftConnection = (ConnectionNode)leftConnectionCharacter;

					EdgeDeclNode leftEdge = leftConnection.Edge;

					if(!leftEdge.Equals(rightEdge))
						continue;

					if(leftConnection.ConnectionKind != rightConnection.ConnectionKind)
					{
						res = false;
						rightConnection.ReportError("Reused edge " + rightEdge + " does not have the same connection kind"
								+ " (in pattern: " + ConnectionNode.toString(leftConnection.ConnectionKind)
								+ ", but in rewrite part: " + ConnectionNode.toString(rightConnection.ConnectionKind) + ").");
						// if you don't add to alreadyReported erroneous errors can occur,
						// e.g. lhs=x-e->y, rhs=y-e-x
						alreadyReported.Add(rightEdge);
					}

					res &= IsLhsRhsReuseOk(alreadyReported, redirectedFrom, redirectedTo,
							right, leftConnection, rightConnection);
				}
			}

			return res;
		}

		private bool IsLhsRhsReuseOk(ICollection<EdgeDeclNode> alreadyReported,
				Dictionary<EdgeDeclNode, NodeDeclNode> redirectedFrom, Dictionary<EdgeDeclNode, NodeDeclNode> redirectedTo,
				RhsDeclNode right, ConnectionNode leftConnection, ConnectionNode rightConnection)
		{
			NodeDeclNode rightSource = rightConnection.Src;
			NodeDeclNode rightTarget = rightConnection.Tgt;

			HashSet<BaseNode> rhsNodes = new HashSet<BaseNode>();
			rhsNodes.AddAll(right.GetNodesToReuse(pattern));

			if(rightSource is NodeTypeChangeDeclNode)
			{
				rightSource = ((NodeTypeChangeDeclNode)rightSource).OldNode;
				rhsNodes.Add(rightSource);
			}
			if(rightTarget is NodeTypeChangeDeclNode)
			{
				rightTarget = ((NodeTypeChangeDeclNode)rightTarget).OldNode;
				rhsNodes.Add(rightTarget);
			}

			bool res = true;

			res &= IsLhsRhsSourceReuseOk(alreadyReported, redirectedFrom, leftConnection, rightConnection, rightSource, rhsNodes);

			res &= IsLhsRhsTargetReuseOk(alreadyReported, redirectedTo, leftConnection, rightConnection, rightTarget, rhsNodes);

			return res;
		}

		private bool IsLhsRhsSourceReuseOk(ICollection<EdgeDeclNode> alreadyReported,
				Dictionary<EdgeDeclNode, NodeDeclNode> redirectedFrom,
				ConnectionNode leftConnection, ConnectionNode rightConnection,
				NodeDeclNode rightSource, HashSet<BaseNode> rhsNodes)
		{
			bool res = true;

			EdgeDeclNode leftEdge = leftConnection.Edge;
			EdgeDeclNode rightEdge = rightConnection.Edge;

			NodeDeclNode leftSource = leftConnection.Src;

			if(!leftSource.IsDummy())
			{
				if(rightSource.IsDummy())
				{
					if(rhsNodes.Contains(leftSource))
					{
						//replace the dummy src node by the src node of the pattern connection
						rightConnection.Src = leftSource;
					}
					else if(!alreadyReported.Contains(rightEdge))
					{
						res = false;
						rightConnection.ReportError("The source node" + leftSource.EmptyWhenAnonymousInParenthesis(" ")
								+ " of reused/referenced edge " + leftEdge + " must be reused/referenced, too.");
						alreadyReported.Add(rightEdge);
					}
				}
				else if(leftSource != rightSource
						&& (rightConnection.RedirectionKind & ConnectionNode.REDIRECT_SOURCE) != ConnectionNode.REDIRECT_SOURCE
						&& !alreadyReported.Contains(rightEdge))
				{
					res = false;
					rightConnection.ReportError("Reused/referenced edge " + leftEdge
							+ " does not connect the same (source) nodes (and is not declared to redirect source)"
							+ DiffersFromSpecification(leftSource, rightSource, false) + ".");
					alreadyReported.Add(rightEdge);
				}
			}

			if((rightConnection.RedirectionKind & ConnectionNode.REDIRECT_SOURCE) == ConnectionNode.REDIRECT_SOURCE)
			{
				if(rightSource.IsDummy())
				{
					res = false;
					rightConnection.ReportError("A source redirection is specified for edge " + leftEdge + ", but no source node is given.");
				}

				if(leftSource.Equals(rightSource))
					rightConnection.ReportWarning("Redirecting edge " + leftEdge + " to the same source node again (" + rightSource + ").");

				if(redirectedFrom.ContainsKey(leftEdge))
				{
					res = false;
					NodeDeclNode rightSource2 = redirectedFrom[leftEdge];
					rightConnection.ReportError("The source of edge " + leftEdge + " is redirected more than once"
							+ " (to " + rightSource.UserFriendlyToString() + " and to " + rightSource2.UserFriendlyToString() + ").");
				}
				redirectedFrom[leftEdge] = rightSource;
			}

			//check, whether RHS "adds" a node to a dangling end of a edge
			if(!alreadyReported.Contains(rightEdge))
			{
				if(leftSource.IsDummy() && !rightSource.IsDummy()
						&& (rightConnection.RedirectionKind & ConnectionNode.REDIRECT_SOURCE) != ConnectionNode.REDIRECT_SOURCE)
				{
					res = false;
					rightConnection.ReportError("Reused edge " + leftEdge + " dangles on LHS,"
							+ " but has a source node on RHS" + rightSource.EmptyWhenAnonymousInParenthesis(" ") + ".");
					alreadyReported.Add(rightEdge);
				}
			}

			return res;
		}

		private bool IsLhsRhsTargetReuseOk(ICollection<EdgeDeclNode> alreadyReported,
				Dictionary<EdgeDeclNode, NodeDeclNode> redirectedTo,
				ConnectionNode leftConnection, ConnectionNode rightConnection, NodeDeclNode rightTarget,
				HashSet<BaseNode> rhsNodes)
		{
			bool res = true;

			EdgeDeclNode leftEdge = leftConnection.Edge;
			EdgeDeclNode rightEdge = rightConnection.Edge;

			NodeDeclNode leftTarget = leftConnection.Tgt;

			if(!leftTarget.IsDummy())
			{
				if(rightTarget.IsDummy())
				{
					if(rhsNodes.Contains(leftTarget))
					{
						//replace the dummy tgt node by the tgt node of the pattern connection
						rightConnection.Tgt = leftTarget;
					}
					else if(!alreadyReported.Contains(rightEdge))
					{
						res = false;
						rightConnection.ReportError("The target node" + leftTarget.EmptyWhenAnonymousInParenthesis(" ")
								+ " of reused/referenced edge " + leftEdge + " must be reused/referenced, too.");
						alreadyReported.Add(rightEdge);
					}
				}
				else if(leftTarget != rightTarget
						&& (rightConnection.RedirectionKind & ConnectionNode.REDIRECT_TARGET) != ConnectionNode.REDIRECT_TARGET
						&& !alreadyReported.Contains(rightEdge))
				{
					res = false;
					rightConnection.ReportError("Reused/referenced edge " + leftEdge
							+ " does not connect the same (target) nodes (and is not declared to redirect target)"
							+ DiffersFromSpecification(leftTarget, rightTarget, false) + ".");
					alreadyReported.Add(rightEdge);
				}
			}

			if((rightConnection.RedirectionKind & ConnectionNode.REDIRECT_TARGET) == ConnectionNode.REDIRECT_TARGET)
			{
				if(rightTarget.IsDummy())
				{
					res = false;
					rightConnection.ReportError("A target redirection is specified for edge " + leftEdge + ", but no target node is given.");
				}

				if(leftTarget.Equals(rightTarget))
					rightConnection.ReportWarning("Redirecting edge " + leftEdge + " to the same target node again (" + rightTarget + ").");

				if(redirectedTo.ContainsKey(leftEdge))
				{
					res = false;
					NodeDeclNode rightTarget2 = redirectedTo[leftEdge];
					rightConnection.ReportError("The target of edge " + leftEdge + " is redirected more than once"
							+ " (to " + rightTarget.UserFriendlyToString() + " and to " + rightTarget2.UserFriendlyToString() + ").");
				}
				redirectedTo[leftEdge] = rightTarget;
			}

			//check, whether RHS "adds" a node to a dangling end of a edge
			if(!alreadyReported.Contains(rightEdge))
			{
				if(leftTarget.IsDummy() && !rightTarget.IsDummy()
						&& (rightConnection.RedirectionKind & ConnectionNode.REDIRECT_TARGET) != ConnectionNode.REDIRECT_TARGET)
				{
					res = false;
					rightConnection.ReportError("Reused edge " + leftEdge + " dangles on LHS,"
							+ " but has a target node on RHS" + rightTarget.EmptyWhenAnonymousInParenthesis(" ") + ".");
					alreadyReported.Add(rightEdge);
				}
			}

			return res;
		}

		/// <summary>
		/// Check that exec parameters are not deleted.
		/// 
		/// The check consider the case that parameters are deleted due to
		/// homomorphic matching.
		/// </summary>
		protected internal virtual bool CheckExecParamsNotDeleted(RhsDeclNode right)
		{
			Debug.Assert(IsResolved());

			bool valid = true;

			ISet<ConstraintDeclNode> deletedElements = right.GetElementsToDelete(pattern);
			ISet<ConstraintDeclNode> maybeDeletedElements = right.GetMaybeDeletedElements(pattern);

			foreach(BaseNode imperativeStatement in right.patternGraph.imperativeStmts.ChildrenExact)
			{
				if(!(imperativeStatement is ExecNode))
					continue;

				ExecNode exec = (ExecNode)imperativeStatement;
				foreach(CallActionNode callAction in exec.callActions.ChildrenExact)
				{
					foreach(ExprNode arg in callAction.@params.ChildrenExact)
					{
						HashSet<ConstraintDeclNode> potentiallyResultingElements = new HashSet<ConstraintDeclNode>();
						arg.GetPotentiallyResultingElements(potentiallyResultingElements);
						foreach(ConstraintDeclNode potentiallyResultingElement in potentiallyResultingElements)
							valid &= CheckExecParamNotDeleted(potentiallyResultingElement, deletedElements, maybeDeletedElements);
					}
				}
			}

			return valid;
		}

		private static bool CheckExecParamNotDeleted(ConstraintDeclNode declNode,
				ISet<ConstraintDeclNode> deletedElements, ISet<ConstraintDeclNode> maybeDeletedElements)
		{
			if(deletedElements.Contains(declNode))
			{
				declNode.ReportError("The deleted " + declNode.Kind + " " + declNode
						+ " is not allowed to be passed to an exec statement.");
				return false;
			}
			else if(maybeDeletedElements.Contains(declNode))
			{
				declNode.maybeDeleted = true;

				if(!declNode.Ident.Annotations.IsFlagSet("maybeDeleted"))
				{
					string errorMessage = "The parameter " + declNode + " of the exec statement may be deleted.";
					errorMessage += " Possibly it is homomorphic with a deleted " + declNode.Kind;
					errorMessage += " (use a [maybeDeleted] annotation if you think that this does not cause problems)";

					if(declNode is EdgeDeclNode)
						errorMessage += ", or " + declNode + " is a dangling edge and a deleted node exists";
					errorMessage += ".";
					declNode.ReportError(errorMessage);

					return false;
				}
			}

			return true;
		}

		//potential TODO: use name of top-level entity, compare with top-level instead of two neighboring levels in nesting tree
		protected internal virtual bool SameNumberOfRewriteParts(RhsDeclNode right, string actionKind)
		{
			bool res = true;

			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					if(right == null && alternativeCase.right != null)
					{
						alternativeCase.ReportError("No rewrite part is specified in the " + actionKind + (ident.CurrOcc.IsAnonymous() ? "" : " " + ident)
								+ ", but one is given in the nested " + alternativeCase.Kind + " " + alternativeCase.ident + ".");
						res = false;
					}
					if(right != null && alternativeCase.right == null)
					{
						alternativeCase.ReportError("A rewrite part is specified in the " + actionKind + (ident.CurrOcc.IsAnonymous() ? "" : " " + ident)
								+ ", but none is given in the nested " + alternativeCase.Kind + " " + alternativeCase.ident + ".");
						res = false;
					}
				}
			}

			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				if(right == null && iterated.right != null)
				{
					iterated.ReportError("No rewrite part is specified in the " + actionKind + (ident.CurrOcc.IsAnonymous() ? "" : " " + ident)
							+ ", but one is given in the nested " + iterated.Kind + iterated.EmptyWhenAnonymousPostfix(" ") + ".");
					res = false;
				}
				if(right != null && iterated.right == null)
				{
					iterated.ReportError("A rewrite part is specified in the " + actionKind + (ident.CurrOcc.IsAnonymous() ? "" : " " + ident)
							+ ", but none is given in the nested " + iterated.Kind + iterated.EmptyWhenAnonymousPostfix(" ") + ".");
					res = false;
				}
			}

			return res;
		}

		protected internal virtual bool NoNestedRewriteParameters(RhsDeclNode right, string actionKind)
		{
			bool res = true;

			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					if(alternativeCase.right == null)
						continue;

					IList<DeclNode> parametersInNestedAlternativeCase = alternativeCase.right.patternGraph.ParamDecls;

					if(parametersInNestedAlternativeCase.Count != 0)
					{
						alternativeCase.ReportError("No rewrite parameters are allowed in nested alternative cases,"
								 + " but " + parametersInNestedAlternativeCase.Count + " are given"
								 + " in " + alternativeCase.ident + ".");
						res = false;
					}
				}
			}

			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				if(iterated.right == null)
					continue;

				IList<DeclNode> parametersInNestedIterated = iterated.right.patternGraph.ParamDecls;

				if(parametersInNestedIterated.Count != 0)
				{
					iterated.ReportError("No rewrite parameters are allowed in nested " + iterated.Kind + " parts,"
							+ " but " + parametersInNestedIterated.Count + " are given"
							+ iterated.EmptyWhenAnonymous(" in " + iterated.ident) + ".");
					res = false;
				}
			}

			return res;
		}

		protected internal virtual bool NoAmbiguousRetypes(RhsDeclNode right)
		{
			if(right == null)
				return false;
			bool result = true;
			foreach(NodeDeclNode node in pattern.Nodes)
			{
				if(node.directlyNestingLHSGraph == pattern)
					result &= NoAmbiguousRetypes(right, node);
			}
			foreach(EdgeDeclNode edge in pattern.Edges)
			{
				if(edge.directlyNestingLHSGraph == pattern)
					result &= NoAmbiguousRetypes(right, edge);
			}
			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
					result &= alternativeCase.NoAmbiguousRetypes(alternativeCase.right);
			}
			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
				result &= iterated.NoAmbiguousRetypes(iterated.right);
			return result;
		}

		protected internal virtual bool NoAmbiguousRetypes(RhsDeclNode right, NodeDeclNode node)
		{
			bool noAmbiguousRetypes = true;
			NodeTypeChangeDeclNode retypeOfNode = null;
			Pair<bool, NodeTypeChangeDeclNode> result = right.RhsGraph.NoAmbiguousRetypes(node, retypeOfNode);
			noAmbiguousRetypes &= result.first;
			retypeOfNode = result.second;
			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				NodeTypeChangeDeclNode tempRetype = null;
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					result = alternativeCase.NoAmbiguousRetypes(alternativeCase.right, node, retypeOfNode);
					noAmbiguousRetypes &= result.first;
					if(tempRetype == null)
						tempRetype = result.second;
				}
				if(retypeOfNode == null)
					retypeOfNode = tempRetype;
			}
			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				result = iterated.NoAmbiguousRetypes(iterated.right, node, retypeOfNode);
				noAmbiguousRetypes &= result.first;
				if(retypeOfNode == null)
					retypeOfNode = result.second;
			}
			return noAmbiguousRetypes;
		}

		protected internal virtual bool NoAmbiguousRetypes(RhsDeclNode right, EdgeDeclNode edge)
		{
			bool noAmbiguousRetypes = true;
			EdgeTypeChangeDeclNode retypeOfEdge = null;
			Pair<bool, EdgeTypeChangeDeclNode> result = right.RhsGraph.NoAmbiguousRetypes(edge, retypeOfEdge);
			noAmbiguousRetypes &= result.first;
			retypeOfEdge = result.second;
			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				EdgeTypeChangeDeclNode tempRetype = null;
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					result = alternativeCase.NoAmbiguousRetypes(alternativeCase.right, edge, retypeOfEdge);
					noAmbiguousRetypes &= result.first;
					if(tempRetype == null)
						tempRetype = result.second;
				}
				if(retypeOfEdge == null)
					retypeOfEdge = tempRetype;
			}
			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				result = iterated.NoAmbiguousRetypes(iterated.right, edge, retypeOfEdge);
				noAmbiguousRetypes &= result.first;
				if(retypeOfEdge == null)
					retypeOfEdge = result.second;
			}
			return noAmbiguousRetypes;
		}

		protected internal virtual Pair<bool, NodeTypeChangeDeclNode> NoAmbiguousRetypes(RhsDeclNode right, NodeDeclNode node, NodeTypeChangeDeclNode retypeOfNode)
		{
			if(right == null)
				return new Pair<bool, NodeTypeChangeDeclNode>(Convert.ToBoolean(false), retypeOfNode);
			bool noAmbiguousRetypes = true;
			Pair<bool, NodeTypeChangeDeclNode> result = right.RhsGraph.NoAmbiguousRetypes(node, retypeOfNode);
			noAmbiguousRetypes &= result.first;
			retypeOfNode = result.second;
			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				NodeTypeChangeDeclNode tempRetype = null;
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					result = alternativeCase.NoAmbiguousRetypes(alternativeCase.right, node, retypeOfNode);
					noAmbiguousRetypes &= result.first;
					if(tempRetype == null)
						tempRetype = result.second;
				}
				if(retypeOfNode == null)
					retypeOfNode = tempRetype;
			}
			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				result = iterated.NoAmbiguousRetypes(iterated.right, node, retypeOfNode);
				noAmbiguousRetypes &= result.first;
				if(retypeOfNode == null)
					retypeOfNode = result.second;
			}
			return new Pair<bool, NodeTypeChangeDeclNode>(Convert.ToBoolean(noAmbiguousRetypes), retypeOfNode);
		}

		protected internal virtual Pair<bool, EdgeTypeChangeDeclNode> NoAmbiguousRetypes(RhsDeclNode right, EdgeDeclNode edge, EdgeTypeChangeDeclNode retypeOfEdge)
		{
			if(right == null)
				return new Pair<bool, EdgeTypeChangeDeclNode>(Convert.ToBoolean(false), retypeOfEdge);
			bool noAmbiguousRetypes = true;
			Pair<bool, EdgeTypeChangeDeclNode> result = right.RhsGraph.NoAmbiguousRetypes(edge, retypeOfEdge);
			noAmbiguousRetypes &= result.first;
			retypeOfEdge = result.second;
			foreach(AlternativeDeclNode alternative in pattern.alts.ChildrenExact)
			{
				EdgeTypeChangeDeclNode tempRetype = null;
				foreach(AlternativeCaseDeclNode alternativeCase in alternative.ChildrenExact)
				{
					result = alternativeCase.NoAmbiguousRetypes(alternativeCase.right, edge, retypeOfEdge);
					noAmbiguousRetypes &= result.first;
					if(tempRetype == null)
						tempRetype = result.second;
				}
				if(retypeOfEdge == null)
					retypeOfEdge = tempRetype;
			}
			foreach(IteratedDeclNode iterated in pattern.iters.ChildrenExact)
			{
				result = iterated.NoAmbiguousRetypes(iterated.right, edge, retypeOfEdge);
				noAmbiguousRetypes &= result.first;
				if(retypeOfEdge == null)
					retypeOfEdge = result.second;
			}
			return new Pair<bool, EdgeTypeChangeDeclNode>(Convert.ToBoolean(noAmbiguousRetypes), retypeOfEdge);
		}

		protected internal virtual void ConstructIRaux(Rule constructedRule, RhsDeclNode right)
		{
			// add Params to the IR
			AddParams(constructedRule);

			// add replacement parameters to the IR
			PatternGraphRhs rightPattern = null;
			if(right != null)
				rightPattern = right.GetIRPatternGraph(pattern.IRPatternGraphLhs);
			else
				return;

			// add replacement parameters to the current graph
			foreach(DeclNode decl in right.patternGraph.ParamDecls)
			{
				if(decl is NodeDeclNode)
				{
					rightPattern.AddReplParameter(decl.CheckIR<Node>(typeof(Node)));
					rightPattern.AddSingleNode(((NodeDeclNode)decl).IRNode);
				}
				else if(decl is VarDeclNode)
				{
					rightPattern.AddReplParameter(decl.CheckIR<Variable>(typeof(Variable)));
					rightPattern.AddVariable(((VarDeclNode)decl).IRVariable);
				}
				else
					throw new ArgumentException("unknown Class: " + decl);
			}

			// and also to the nested alternatives and iterateds
			AddReplacementParamsToNestedAlternativesAndIterateds(constructedRule, right);
		}

		protected internal virtual void AddParams(MatchingAction constructedMatchingAction)
		{
			PatternGraphLhs patternGraph = constructedMatchingAction.Pattern;

			foreach(DeclNode decl in pattern.ParamDecls)
			{
				Entity entity = decl.CheckIR<Entity>(typeof(Entity));
				if(entity.IsDefToBeYieldedTo())
					constructedMatchingAction.AddDefParameter(entity);
				else
					constructedMatchingAction.AddParameter(entity);

				if(decl is VarDeclNode)
					patternGraph.AddVariable(((VarDeclNode)decl).IRVariable);
			}
		}

		protected internal static void AddReplacementParamsToNestedAlternativesAndIterateds(Rule constructedRule, RhsDeclNode right)
		{
			// add replacement parameters to the nested alternatives and iterateds
			PatternGraphLhs patternGraph = constructedRule.Pattern;
			foreach(DeclNode decl in right.patternGraph.ParamDecls)
			{
				if(decl is NodeDeclNode)
					AddReplacementNodeParamToNestedAlternativesAndIterateds((NodeDeclNode)decl, patternGraph);
				else if(decl is VarDeclNode)
					AddReplacementVarParamToNestedAlternativesAndIterateds((VarDeclNode)decl, patternGraph);
				else
					throw new ArgumentException("unknown Class: " + decl);
			}
		}

		private static void AddReplacementNodeParamToNestedAlternativesAndIterateds(NodeDeclNode decl, PatternGraphLhs patternGraph)
		{
			foreach(Alternative alternative in patternGraph.Alts)
			{
				foreach(Rule alternativeCase in alternative.AlternativeCases)
				{
					alternativeCase.Right.AddReplParameter(decl.CheckIR<Node>(typeof(Node)));
					alternativeCase.Right.AddSingleNode(decl.IRNode);
				}
			}
			foreach(Rule iterated in patternGraph.Iters)
			{
				iterated.Right.AddReplParameter(decl.CheckIR<Node>(typeof(Node)));
				iterated.Right.AddSingleNode(decl.IRNode);
			}
		}

		private static void AddReplacementVarParamToNestedAlternativesAndIterateds(VarDeclNode decl, PatternGraphLhs patternGraph)
		{
			foreach(Alternative alternative in patternGraph.Alts)
			{
				foreach(Rule alternativeCase in alternative.AlternativeCases)
				{
					alternativeCase.Right.AddReplParameter(decl.CheckIR<Variable>(typeof(Variable)));
					alternativeCase.Right.AddVariable(decl.IRVariable);
				}
			}
			foreach(Rule iterated in patternGraph.Iters)
			{
				iterated.Right.AddReplParameter(decl.CheckIR<Variable>(typeof(Variable)));
				iterated.Right.AddVariable(decl.IRVariable);
			}
		}

		/// <summary>
		/// add NACs for induced- or DPO-semantic
		/// </summary>
		protected internal virtual void ConstructImplicitNegs(PatternGraphLhs left)
		{
			PatternGraphLhsNode leftNode = pattern;
			ImplicitNegComputer implicitNegComputer = new ImplicitNegComputer(leftNode);
			ImplicitNegComputerInduced implicitNegComputerInduced = new ImplicitNegComputerInduced(leftNode);

			foreach(PatternGraphLhs neg in implicitNegComputer.ImplicitNegGraphs)
				left.AddNegGraph(neg);
			foreach(PatternGraphLhs neg in implicitNegComputerInduced.ImplicitNegGraphs)
				left.AddNegGraph(neg);
		}

		// TODO use this to create IR patterns, that is currently not supported by
		//      any backend
		/*private IR constructPatternIR() {
			PatternGraph left = pattern.getPatternGraph();
	
			// return if the pattern graph already constructed the IR object
			// that may happens in recursive patterns
			if (isIRAlreadySet()) {
				return getIR();
			}
	
			List<PatternGraph> right = new ArrayList<PatternGraph>();
			for (int i = 0; i < this.right.children.size(); i++) {
				right.add(this.right.children.get(i).getPatternGraph(left));
			}
	
			// return if the pattern graph already constructed the IR object
			// that may happens in recursive patterns
			if (isIRAlreadySet()) {
				return getIR();
			}
	
			Pattern pattern = new Pattern(getIdentNode().getIdent(), left, right);
	
			constructImplicitNegs(left);
			constructIRaux(pattern);
	
			// add Eval statements to the IR
			for (int i = 0; i < this.right.children.size(); i++) {
				for (Assignment n : this.right.children.get(i).getAssignments()) {
					pattern.addEval(i,n);
				}
			}
	
			return pattern;
		}*/
	}

}
