/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// Generates the eval statements for the SearchPlanBackend2 backend.
/// @author Moritz Kroll, Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.be.Csharp
{

using System.Collections.Generic;
using System.Diagnostics;

using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
using de.unika.ipd.grgen.ir;
using Needs = de.unika.ipd.grgen.ir.NeededEntities.Needs;
using Expression = de.unika.ipd.grgen.ir.expr.Expression;
using Qualification = de.unika.ipd.grgen.ir.expr.Qualification;
using Model = de.unika.ipd.grgen.ir.model.Model;
using InheritanceType = de.unika.ipd.grgen.ir.model.type.InheritanceType;
using Edge = de.unika.ipd.grgen.ir.pattern.Edge;
using GraphEntity = de.unika.ipd.grgen.ir.pattern.GraphEntity;
using Node = de.unika.ipd.grgen.ir.pattern.Node;
using ExecStatement = de.unika.ipd.grgen.ir.stmt.ExecStatement;
using ImperativeStmt = de.unika.ipd.grgen.ir.stmt.ImperativeStmt;
using DefinedMatchType = de.unika.ipd.grgen.ir.type.DefinedMatchType;
using MatchType = de.unika.ipd.grgen.ir.type.MatchType;
using de.unika.ipd.grgen.util.collection;
using SourceBuilder = de.unika.ipd.grgen.util.SourceBuilder;

// generates calls to the routines implementing the execs, whose representations were generated by ActionsExecGen (and whose real implementations will be generated in engine-net-2)
public class ModifyExecGen : CSharpBase
{
	internal Model model;
	internal SearchPlanBackend2 be;

	internal int xgrsID;

	public ModifyExecGen(SearchPlanBackend2 backend, string nodeTypePrefix, string edgeTypePrefix, string objectTypePrefix, string transientObjectTypePrefix)
		: base(nodeTypePrefix, edgeTypePrefix, objectTypePrefix, transientObjectTypePrefix)
	{
		be = backend;
		model = be.unit.ActionsGraphModel;

		xgrsID = 0;
	}

	public virtual void GenExecStatement(SourceBuilder sb, ModifyGenerationStateConst state, ExecStatement es)
	{
		Exec exec = es.Exec;
		foreach(Entity neededEntity in exec.GetNeededEntities(true))
		{
			if(neededEntity.IsDefToBeYieldedTo())
			{
				if(neededEntity is GraphEntity)
				{
					sb.AppendFront(FormatElementInterfaceRef(neededEntity.Type) + " ");
					sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + " = ");
					sb.Append("(" + FormatElementInterfaceRef(neededEntity.Type) + ")");
					sb.Append(FormatEntity(neededEntity) + ";\n");
				}
				else
				{ // if(neededEntity instanceof Variable)
					sb.AppendFront(FormatAttributeType(neededEntity.Type) + " ");
					sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + " = ");
					sb.Append("(" + FormatAttributeType(neededEntity.Type) + ")");
					sb.Append(FormatEntity(neededEntity) + ";\n");
				}
			}
		}
		sb.AppendFront("ApplyXGRS_" + state.Name + "_" + xgrsID
				+ "((GRGEN_LGSP.LGSPGraphProcessingEnvironment)actionEnv");
		foreach(Entity neededEntity in exec.GetNeededEntities(true))
		{
			if(!neededEntity.IsDefToBeYieldedTo())
			{
				sb.Append(", ");
				if(neededEntity.Type is InheritanceType)
					sb.Append("(" + FormatElementInterfaceRef(neededEntity.Type) + ")");
				sb.Append(FormatEntity(neededEntity));
			}
		}
		foreach(Entity neededEntity in exec.GetNeededEntities(true))
		{
			if(neededEntity.IsDefToBeYieldedTo())
			{
				sb.Append(", ref ");
				sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID);
			}
		}
		sb.Append(");\n");
		foreach(Entity neededEntity in exec.GetNeededEntities(true))
		{
			if(neededEntity.IsDefToBeYieldedTo())
			{
				sb.AppendFront(FormatEntity(neededEntity) + " = ");
				if((neededEntity.Context & BaseNode.CONTEXT_COMPUTATION) != BaseNode.CONTEXT_COMPUTATION)
				{
					if(neededEntity is Node)
						sb.Append("(GRGEN_LGSP.LGSPNode)");
					else if(neededEntity is Edge)
						sb.Append("(GRGEN_LGSP.LGSPEdge)");
				}
				sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + ";\n");
			}
		}

		++xgrsID;
	}

	public virtual void GenImperativeStatements(SourceBuilder sb, ModifyGenerationTask task,
			ModifyGenerationState state, ModifyGenerationStateConst stateConst, NeededEntities needsInput,
			string pathPrefix, string packagePrefixedActionName)
	{
		if(state.EmitProfilingInstrumentation() && pathPrefix.Equals("")
				&& !task.isSubpattern && task.typeOfTask == ModifyGenerationTask.TYPE_OF_TASK_MODIFY)
			GenExecProfilingStart(sb);

		if(!task.mightThereBeDeferredExecs)
		{ // procEnv was already emitted in case of deferred execs
			if(task.right.ImperativeStmts.Count > 0)
			{ // we need it?
				// see genSubpatternModificationCalls why not simply emitting in case of !task.right.getImperativeStmts().isEmpty()
				if(!task.IsEmitHereNeeded())
					sb.AppendFront("GRGEN_LGSP.LGSPGraphProcessingEnvironment procEnv = (GRGEN_LGSP.LGSPGraphProcessingEnvironment)actionEnv;\n");
			}
		}

		if(task.mightThereBeDeferredExecs)
			sb.AppendFront("procEnv.sequencesManager.ExecuteDeferredSequencesThenExitRuleModify(procEnv);\n");

		state.ClearContainerExprs();
		foreach(ImperativeStmt istmt in task.right.ImperativeStmts)
		{
			NeededEntities needs = new NeededEntities(EnumSet.Of(Needs.CONTAINER_EXPRS));
			CollectContainerExprsNeededByImperativeStatement(istmt, needs);
			state.InitNeeds(needs.containerExprs);

			sb.AppendFront("{\n");
			sb.Indent();
			GenContainerVariablesBeforeImperativeStatement(sb, state);

			state.useVarForResult_ = true;
			GenImperativeStatement(sb, stateConst, task, istmt, pathPrefix);
			state.useVarForResult_ = false;

			sb.Unindent();
			sb.AppendFront("}\n");

			state.ClearContainerExprs();
		}

		if(state.EmitProfilingInstrumentation() && pathPrefix.Equals("")
				&& !task.isSubpattern && task.typeOfTask == ModifyGenerationTask.TYPE_OF_TASK_MODIFY)
			GenExecProfilingStop(sb, packagePrefixedActionName);
	}

	private static void GenExecProfilingStart(SourceBuilder sb)
	{
		sb.AppendFront("long searchStepsAtBeginExec = actionEnv.PerformanceInfo.SearchSteps;\n");
	}

	private static void CollectContainerExprsNeededByImperativeStatement(ImperativeStmt istmt,
			NeededEntities needs)
	{
		if(istmt is Emit)
		{
			Emit emit = (Emit)istmt;
			foreach(Expression arg in emit.Arguments)
				arg.CollectNeededEntities(needs);
		}
	}

	private void GenContainerVariablesBeforeImperativeStatement(SourceBuilder sb, ModifyGenerationState state)
	{
		// the container expressions are visited and inserted into the LinkedHashSet from the needs in preorder, and transferred to a LinkedHashMap in iteration order
		List<Pair<Expression, string>> array = new List<Pair<Expression, string>>();
		foreach(KeyValuePair<Expression, string> entry in state.MapExprToTempVar.SetOfKeyValuePairs())
			array.Add(new Pair<Expression, string>(entry.Key, entry.Value));

		// iterate in reverse order so that contained container expressions are evaluated before their containing expressions
		for(int i = array.Count - 1; i >= 0; --i)
		{
			Expression expr = array[i].first;
			string varName = array[i].second;
			sb.AppendFront(FormatAttributeType(expr.Type) + " " + varName + " = ");

			state.switchToVarForResultAfterFirstVarUsage_ = true;
			GenExpression(sb, expr, state);
			state.switchToVarForResultAfterFirstVarUsage_ = false;
			state.useVarForResult_ = false;

			sb.Append(";\n");
		}
	}

	private void GenImperativeStatement(SourceBuilder sb, ModifyGenerationStateConst state,
			ModifyGenerationTask task, ImperativeStmt istmt, string pathPrefix)
	{
		if(istmt is Emit)
		{
			Emit emit = (Emit)istmt;
			GenEmit(sb, state, emit);
		}
		else if(istmt is Exec)
		{
			Exec exec = (Exec)istmt;
			GenExec(sb, task, pathPrefix, exec);
		}
		else
			Debug.Assert(false, "unknown ImperativeStmt: " + istmt + " in " + task.left.NameOfGraph);
	}

	private static void GenExecProfilingStop(SourceBuilder sb, string packagePrefixedActionName)
	{
		sb.AppendFront("actionEnv.PerformanceInfo.ActionProfiles[\"" + packagePrefixedActionName
				+ "\"].searchStepsDuringExecTotal");
		sb.Append(" += actionEnv.PerformanceInfo.SearchSteps - searchStepsAtBeginExec;\n");
	}

	public virtual void GenEmit(SourceBuilder sb, ModifyGenerationStateConst state, Emit emit)
	{
		string emitWriter = emit.IsDebug() ? "EmitWriterDebug" : "EmitWriter";
		foreach(Expression arg in emit.Arguments)
		{
			sb.AppendFront("procEnv." + emitWriter + ".Write(");
			sb.Append("GRGEN_LIBGR.EmitHelper.ToStringNonNull(");
			GenExpression(sb, arg, state);
			sb.Append(", graph, null, null, null)");
			sb.Append(");\n");
		}
	}

	private void GenExec(SourceBuilder sb, ModifyGenerationTask task, string pathPrefix, Exec exec)
	{
		if(task.isSubpattern || !string.ReferenceEquals(pathPrefix, ""))
		{
			string closureName = "XGRSClosure_" + pathPrefix + task.left.NameOfGraph + "_" + xgrsID;
			sb.AppendFront(closureName + " xgrs" + xgrsID + " = "
					+ "new " + closureName + "(");
			bool first = true;
			foreach(Entity neededEntity in exec.GetNeededEntities(false))
			{
				if(first)
					first = false;
				else
					sb.Append(", ");
				if(neededEntity.Type is InheritanceType)
					sb.Append("(" + FormatElementInterfaceRef(neededEntity.Type) + ")");
				sb.Append(FormatEntity(neededEntity));
			}
			sb.Append(");\n");
			sb.AppendFront("procEnv.sequencesManager.AddDeferredSequence(xgrs" + xgrsID + ");\n");
		}
		else
		{
			foreach(Entity neededEntity in exec.GetNeededEntities(false))
			{
				if(neededEntity.IsDefToBeYieldedTo())
				{
					if(neededEntity is GraphEntity)
					{
						sb.AppendFront(FormatElementInterfaceRef(neededEntity.Type) + " ");
						sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + " = ");
						sb.Append("(" + FormatElementInterfaceRef(neededEntity.Type) + ")");
						sb.Append(FormatEntity(neededEntity) + ";\n");
					}
					else
					{ // if(neededEntity instanceof Variable)
						sb.AppendFront(FormatAttributeType(neededEntity.Type) + " ");
						sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + " = ");
						sb.Append("(" + FormatAttributeType(neededEntity.Type) + ")");
						sb.Append(FormatEntity(neededEntity) + ";\n");
					}
				}
			}
			sb.AppendFront("ApplyXGRS_" + task.left.NameOfGraph + "_" + xgrsID + "(procEnv");
			foreach(Entity neededEntity in exec.GetNeededEntities(false))
			{
				if(!neededEntity.IsDefToBeYieldedTo())
				{
					sb.Append(", ");
					if(neededEntity.Type is InheritanceType)
						sb.Append("(" + FormatElementInterfaceRef(neededEntity.Type) + ")");
					sb.Append(FormatEntity(neededEntity));
				}
			}
			foreach(Entity neededEntity in exec.GetNeededEntities(false))
			{
				if(neededEntity.IsDefToBeYieldedTo())
				{
					sb.Append(", ref ");
					sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID);
				}
			}
			sb.Append(");\n");
			foreach(Entity neededEntity in exec.GetNeededEntities(false))
			{
				if(neededEntity.IsDefToBeYieldedTo())
				{
					sb.AppendFront(FormatEntity(neededEntity) + " = ");
					if((neededEntity.Context & BaseNode.CONTEXT_COMPUTATION) != BaseNode.CONTEXT_COMPUTATION)
					{
						if(neededEntity is Node)
							sb.Append("(GRGEN_LGSP.LGSPNode)");
						else if(neededEntity is Edge)
							sb.Append("(GRGEN_LGSP.LGSPEdge)");
					}
					sb.Append("tmp_" + FormatEntity(neededEntity) + "_" + xgrsID + ";\n");
				}
			}
		}
		/*		for(Expression arg : exec.getArguments()) {
					if(!(arg instanceof GraphEntityExpression)) continue;
					sb.append(", ");
					genExpression(sb, arg, state);
				}*/

		++xgrsID;
	}

	//////////////////////
	// Expression stuff //
	//////////////////////

	protected internal override void GenQualAccess(SourceBuilder sb, Qualification qual, object modifyGenerationState)
	{
		GenQualAccess(sb, qual, (ModifyGenerationStateConst)modifyGenerationState);
	}

	private void GenQualAccess(SourceBuilder sb, Qualification qual, ModifyGenerationStateConst state)
	{
		Entity owner = qual.Owner;
		Entity member = qual.Member;
		if(owner.Type is MatchType || owner.Type is DefinedMatchType)
			sb.Append(FormatEntity(owner) + "." + FormatEntity(member));
		else
			GenQualAccess(sb, state, owner, member);
	}

	private void GenQualAccess(SourceBuilder sb, ModifyGenerationStateConst state, Entity owner, Entity member)
	{
		if(!Expression.IsGlobalVariable(owner))
		{
			if(state == null)
			{
				Debug.Assert(false);
				sb.Append(FormatEntity(owner) + ".@" + FormatIdentifiable(member));
				return;
			}

			if(AccessViaVariable(state, owner, member))
				sb.Append("tempvar_" + FormatEntity(owner) + "_" + FormatIdentifiable(member));
			else
			{
				if(AccessViaInterface(state, owner))
					sb.Append("i");

				sb.Append(FormatEntity(owner) + ".@" + FormatIdentifiable(member));
			}
		}
		else
		{
			sb.Append(FormatGlobalVariableRead(owner));
			sb.Append(".@" + FormatIdentifiable(member));
		}
	}

	protected internal override void GenMemberAccess(SourceBuilder sb, Entity member)
	{
		// needed in implementing methods
		sb.Append("@" + FormatIdentifiable(member));
	}
}

}
