/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ast.decl.pattern
{

	using System.Collections.Generic;
	using System.Diagnostics;

	using BaseNode = de.unika.ipd.grgen.ast.BaseNode;
	using IdentNode = de.unika.ipd.grgen.ast.IdentNode;
	using NestedMatcherDeclNode = de.unika.ipd.grgen.ast.decl.executable.NestedMatcherDeclNode;
	using FilterAutoGeneratedDeclNode = de.unika.ipd.grgen.ast.decl.executable.FilterAutoGeneratedDeclNode;
	using FilterAutoDeclNode = de.unika.ipd.grgen.ast.decl.executable.FilterAutoDeclNode;
	using FilterAutoSuppliedDeclNode = de.unika.ipd.grgen.ast.decl.executable.FilterAutoSuppliedDeclNode;
	using PatternGraphLhsNode = de.unika.ipd.grgen.ast.pattern.PatternGraphLhsNode;
	using IteratedTypeNode = de.unika.ipd.grgen.ast.type.IteratedTypeNode;
	using TypeNode = de.unika.ipd.grgen.ast.type.TypeNode;
	using de.unika.ipd.grgen.ast.util;
	using IR = de.unika.ipd.grgen.ir.IR;
	using FilterAutoGenerated = de.unika.ipd.grgen.ir.executable.FilterAutoGenerated;
	using FilterAutoSupplied = de.unika.ipd.grgen.ir.executable.FilterAutoSupplied;
	using Rule = de.unika.ipd.grgen.ir.executable.Rule;
	using PatternGraphLhs = de.unika.ipd.grgen.ir.pattern.PatternGraphLhs;
	using PatternGraphRhs = de.unika.ipd.grgen.ir.pattern.PatternGraphRhs;
	using EvalStatements = de.unika.ipd.grgen.ir.stmt.EvalStatements;

	/// <summary>
	/// AST node for an iterated-like pattern (iterated, optional, multiple, iterated-minmax), maybe including replacements.
	/// </summary>
	public abstract class IteratedDeclNode : NestedMatcherDeclNode
	{
		static IteratedDeclNode()
		{
			SetClassName(typeof(IteratedDeclNode), "iterated-cardinality");
		}

		protected internal IteratedTypeNode type;
		protected internal List<FilterAutoDeclNode> filters;

		/// <summary>
		/// Type for this declaration. </summary>
		protected internal static IteratedTypeNode iteratedType = new IteratedTypeNode();

		/// <summary>
		/// Make a new iterated-like rule. </summary>
		/// <param name="left"> The left hand side (The pattern to match). </param>
		/// <param name="right"> The right hand side. </param>
		protected internal IteratedDeclNode(IdentNode id, PatternGraphLhsNode left, RhsDeclNode right)
			: base(id, iteratedType, left, right)
		{
			this.filters = new List<FilterAutoDeclNode>();
		}

		public virtual void AddFilters(List<FilterAutoDeclNode> filters)
		{
			this.filters.AddRange(filters);
		}

		/// <summary>
		/// returns children of this node </summary>
		public override ICollection<BaseNode> Children
		{
			get
			{
				IList<BaseNode> children = new List<BaseNode>();
				children.Add(ident);
				children.Add(GetValidVersion(typeUnresolved, type));
				children.Add(pattern);
				if(right != null)
					children.Add(right);
				return children;
			}
		}

		/// <summary>
		/// returns names of the children, same order as in getChildren </summary>
		public override ICollection<string> ChildrenNames
		{
			get
			{
				IList<string> childrenNames = new List<string>();
				childrenNames.Add("ident");
				childrenNames.Add("type");
				childrenNames.Add("pattern");
				if(right != null)
					childrenNames.Add("right");
				return childrenNames;
			}
		}

		private static readonly DeclarationTypeResolver<IteratedTypeNode> typeResolver =
				new DeclarationTypeResolver<IteratedTypeNode>(typeof(IteratedTypeNode));

		/// <seealso cref="de.unika.ipd.grgen.ast.BaseNode.resolveLocal() "/>
		protected internal override bool ResolveLocal()
		{
			type = typeResolver.Resolve(typeUnresolved, this);

			return type != null
					& ResolveFilters(filters);
		}

		protected internal override bool CheckLocal()
		{
			return base.CheckLocal()
					& CheckFilters(pattern, filters);
		}

		protected internal abstract int MinMatches {get;}
		protected internal abstract int MaxMatches {get;}

		/// <seealso cref="de.unika.ipd.grgen.ast.BaseNode.constructIR()"/>
		protected internal override IR ConstructIR()
		{
			// return if the pattern graph already constructed the IR object
			// that may happen in recursive patterns (and other usages/references)
			if(IsIRAlreadySet())
				return IR;

			Rule iteratedRule = new Rule(Ident.IRIdent, MinMatches, MaxMatches);

			// mark this node as already visited
			IR = iteratedRule;

			PatternGraphLhs left = pattern.IRPatternGraphLhs;

			PatternGraphRhs rightPattern = null;
			if(this.right != null)
				rightPattern = this.right.GetIRPatternGraph(left);

			iteratedRule.Initialize(left, rightPattern);

			ConstructImplicitNegs(left);
			ConstructIRaux(iteratedRule, right);

			// filters add themselves to the iterated rule when their IR is constructed
			foreach(FilterAutoDeclNode filter in filters)
			{
				if(filter is FilterAutoSuppliedDeclNode)
					((FilterAutoSuppliedDeclNode)filter).CheckIR<FilterAutoSupplied>(typeof(FilterAutoSupplied));
				else
					((FilterAutoGeneratedDeclNode)filter).CheckIR<FilterAutoGenerated>(typeof(FilterAutoGenerated));
			}

			// add Eval statements to the IR
			if(this.right != null)
			{
				foreach(EvalStatements evalStatements in this.right.RhsGraph.EvalStatements)
					iteratedRule.AddEval(evalStatements);
			}

			return iteratedRule;
		}

		public override TypeNode DeclType
		{
			get
			{
				Debug.Assert(IsResolved());

				return iteratedType;
			}
		}

		public static new string KindStr
		{
			get
			{
				return "iterated-cardinality";
			}
		}
	}

}
