/*
 * GrGen: graph rewrite generator tool -- release GrGen.NET 8.1
 * Copyright (C) 2003-2026 Universitaet Karlsruhe, Institut fuer Programmstrukturen und Datenorganisation, LS Goos; and free programmers
 * licensed under LGPL v3, some components/parts use different licenses (see LICENSE.txt included in the packaging of this file)
 * www.grgen.de / www.grgen.net
 */

/// <summary>
/// @author Moritz Kroll, Edgar Jakumeit
/// </summary>

namespace de.unika.ipd.grgen.ir.stmt
{
using de.unika.ipd.grgen.ir;
using Edge = de.unika.ipd.grgen.ir.pattern.Edge;
using Node = de.unika.ipd.grgen.ir.pattern.Node;
using OrderedReplacement = de.unika.ipd.grgen.ir.pattern.OrderedReplacement;
using RetypedEdge = de.unika.ipd.grgen.ir.pattern.RetypedEdge;
using RetypedNode = de.unika.ipd.grgen.ir.pattern.RetypedNode;
using Variable = de.unika.ipd.grgen.ir.pattern.Variable;

// too much dedicated assignment statements depending on LHS
// -> TODO: replace by one assignment statement plus LHS expressions denoting the target (two needed because of change assignment with two LHS expressions)
public abstract class EvalStatement : IR, OrderedReplacement
{
	internal EvalStatement next; // may contain following statement, generated by optimization pass breaking up expressions

	public EvalStatement(string name)
		: base(name)
	{
	}

	public virtual EvalStatement Next
	{
		get
		{
		return next;
		}
		set
		{
		this.next = value;
		}
	}


	/// <summary>
	/// Method collectNeededEntities extracts the nodes, edges, and variables occurring in this EvalStatement.
	/// We don't collect global variables (::-prefixed), as no entities and no processing are needed for them at all, they are only accessed. </summary>
	/// <param name="needs"> A NeededEntities instance aggregating the needed elements. </param>
	public virtual void CollectNeededEntities(NeededEntities needs)
	{
		// default implementation for statements without children that need to be collected
	}

	public static bool IsGlobalVariable(Entity entity)
	{
		if(entity is Node && !(entity is RetypedNode))
			return ((Node)entity).directlyNestingLHSGraph == null;
		else if(entity is Edge && !(entity is RetypedEdge))
			return ((Edge)entity).directlyNestingLHSGraph == null;
		else if(entity is Variable)
			return ((Variable)entity).directlyNestingLHSGraph == null;
		return false;
	}
}

}
